// Code generated by tools/proto/build.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_id_s2s.proto

package msgid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client向Server发送消息
type MsgIDS2S int32

const (
	MsgIDS2S_S2SNone          MsgIDS2S = 0
	MsgIDS2S_S2SReqLogin      MsgIDS2S = 1
	MsgIDS2S_S2SGameState     MsgIDS2S = 7
	MsgIDS2S_S2SReqRoleOnline MsgIDS2S = 8
	MsgIDS2S_S2SResRoleOnline MsgIDS2S = 9
	MsgIDS2S_S2SReqConfig     MsgIDS2S = 10
	MsgIDS2S_S2SResConfig     MsgIDS2S = 11
	MsgIDS2S_S2SKickAcc       MsgIDS2S = 12
	MsgIDS2S_S2SKickRole      MsgIDS2S = 13
	MsgIDS2S_S2SRelayToRole   MsgIDS2S = 14
	MsgIDS2S_S2SOfflineEvt    MsgIDS2S = 15
	MsgIDS2S_S2SRoleOffline   MsgIDS2S = 16
)

// Enum value maps for MsgIDS2S.
var (
	MsgIDS2S_name = map[int32]string{
		0:  "S2SNone",
		1:  "S2SReqLogin",
		7:  "S2SGameState",
		8:  "S2SReqRoleOnline",
		9:  "S2SResRoleOnline",
		10: "S2SReqConfig",
		11: "S2SResConfig",
		12: "S2SKickAcc",
		13: "S2SKickRole",
		14: "S2SRelayToRole",
		15: "S2SOfflineEvt",
		16: "S2SRoleOffline",
	}
	MsgIDS2S_value = map[string]int32{
		"S2SNone":          0,
		"S2SReqLogin":      1,
		"S2SGameState":     7,
		"S2SReqRoleOnline": 8,
		"S2SResRoleOnline": 9,
		"S2SReqConfig":     10,
		"S2SResConfig":     11,
		"S2SKickAcc":       12,
		"S2SKickRole":      13,
		"S2SRelayToRole":   14,
		"S2SOfflineEvt":    15,
		"S2SRoleOffline":   16,
	}
)

func (x MsgIDS2S) Enum() *MsgIDS2S {
	p := new(MsgIDS2S)
	*p = x
	return p
}

func (x MsgIDS2S) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgIDS2S) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_id_s2s_proto_enumTypes[0].Descriptor()
}

func (MsgIDS2S) Type() protoreflect.EnumType {
	return &file_msg_id_s2s_proto_enumTypes[0]
}

func (x MsgIDS2S) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgIDS2S.Descriptor instead.
func (MsgIDS2S) EnumDescriptor() ([]byte, []int) {
	return file_msg_id_s2s_proto_rawDescGZIP(), []int{0}
}

var File_msg_id_s2s_proto protoreflect.FileDescriptor

var file_msg_id_s2s_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x32, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x2a, 0xe6, 0x01, 0x0a, 0x08, 0x4d, 0x73,
	0x67, 0x49, 0x44, 0x53, 0x32, 0x53, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x32, 0x53, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x32, 0x53, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x32, 0x53, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x10, 0x07, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x32, 0x53, 0x52, 0x65, 0x71,
	0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x08, 0x12, 0x14, 0x0a, 0x10,
	0x53, 0x32, 0x53, 0x52, 0x65, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x10, 0x09, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x32, 0x53, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x32, 0x53, 0x52, 0x65, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x32, 0x53, 0x4b, 0x69, 0x63,
	0x6b, 0x41, 0x63, 0x63, 0x10, 0x0c, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x32, 0x53, 0x4b, 0x69, 0x63,
	0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x32, 0x53, 0x52, 0x65,
	0x6c, 0x61, 0x79, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x10, 0x0e, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x32, 0x53, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x76, 0x74, 0x10, 0x0f, 0x12, 0x12,
	0x0a, 0x0e, 0x53, 0x32, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x10, 0x10, 0x42, 0x0b, 0x48, 0x03, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_id_s2s_proto_rawDescOnce sync.Once
	file_msg_id_s2s_proto_rawDescData = file_msg_id_s2s_proto_rawDesc
)

func file_msg_id_s2s_proto_rawDescGZIP() []byte {
	file_msg_id_s2s_proto_rawDescOnce.Do(func() {
		file_msg_id_s2s_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_id_s2s_proto_rawDescData)
	})
	return file_msg_id_s2s_proto_rawDescData
}

var file_msg_id_s2s_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_id_s2s_proto_goTypes = []interface{}{
	(MsgIDS2S)(0), // 0: msgid.MsgIDS2S
}
var file_msg_id_s2s_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_id_s2s_proto_init() }
func file_msg_id_s2s_proto_init() {
	if File_msg_id_s2s_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_id_s2s_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_id_s2s_proto_goTypes,
		DependencyIndexes: file_msg_id_s2s_proto_depIdxs,
		EnumInfos:         file_msg_id_s2s_proto_enumTypes,
	}.Build()
	File_msg_id_s2s_proto = out.File
	file_msg_id_s2s_proto_rawDesc = nil
	file_msg_id_s2s_proto_goTypes = nil
	file_msg_id_s2s_proto_depIdxs = nil
}
