// Code generated by tools/proto/build.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_id_s2c.proto

package msgid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client向Server发送消息
type MsgIDS2C int32

const (
	MsgIDS2C_S2CNone       MsgIDS2C = 0
	MsgIDS2C_S2CInit       MsgIDS2C = 1
	MsgIDS2C_S2CHeartBeat  MsgIDS2C = 2
	MsgIDS2C_S2CGateHandle MsgIDS2C = 100
	MsgIDS2C_S2CLogin      MsgIDS2C = 101
	MsgIDS2C_S2CKickRole   MsgIDS2C = 103
	MsgIDS2C_S2CDayChange  MsgIDS2C = 104
	MsgIDS2C_S2CDataReset  MsgIDS2C = 105
	MsgIDS2C_S2CEcho       MsgIDS2C = 106
)

// Enum value maps for MsgIDS2C.
var (
	MsgIDS2C_name = map[int32]string{
		0:   "S2CNone",
		1:   "S2CInit",
		2:   "S2CHeartBeat",
		100: "S2CGateHandle",
		101: "S2CLogin",
		103: "S2CKickRole",
		104: "S2CDayChange",
		105: "S2CDataReset",
		106: "S2CEcho",
	}
	MsgIDS2C_value = map[string]int32{
		"S2CNone":       0,
		"S2CInit":       1,
		"S2CHeartBeat":  2,
		"S2CGateHandle": 100,
		"S2CLogin":      101,
		"S2CKickRole":   103,
		"S2CDayChange":  104,
		"S2CDataReset":  105,
		"S2CEcho":       106,
	}
)

func (x MsgIDS2C) Enum() *MsgIDS2C {
	p := new(MsgIDS2C)
	*p = x
	return p
}

func (x MsgIDS2C) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgIDS2C) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_id_s2c_proto_enumTypes[0].Descriptor()
}

func (MsgIDS2C) Type() protoreflect.EnumType {
	return &file_msg_id_s2c_proto_enumTypes[0]
}

func (x MsgIDS2C) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgIDS2C.Descriptor instead.
func (MsgIDS2C) EnumDescriptor() ([]byte, []int) {
	return file_msg_id_s2c_proto_rawDescGZIP(), []int{0}
}

var File_msg_id_s2c_proto protoreflect.FileDescriptor

var file_msg_id_s2c_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x32, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x2a, 0x99, 0x01, 0x0a, 0x08, 0x4d, 0x73,
	0x67, 0x49, 0x44, 0x53, 0x32, 0x43, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74,
	0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x47, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x10, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x10, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x32, 0x43, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x6f,
	0x6c, 0x65, 0x10, 0x67, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x44, 0x61, 0x79, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x10, 0x68, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x65, 0x74, 0x10, 0x69, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x32, 0x43, 0x45,
	0x63, 0x68, 0x6f, 0x10, 0x6a, 0x42, 0x0b, 0x48, 0x03, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x73, 0x67,
	0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_id_s2c_proto_rawDescOnce sync.Once
	file_msg_id_s2c_proto_rawDescData = file_msg_id_s2c_proto_rawDesc
)

func file_msg_id_s2c_proto_rawDescGZIP() []byte {
	file_msg_id_s2c_proto_rawDescOnce.Do(func() {
		file_msg_id_s2c_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_id_s2c_proto_rawDescData)
	})
	return file_msg_id_s2c_proto_rawDescData
}

var file_msg_id_s2c_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_id_s2c_proto_goTypes = []interface{}{
	(MsgIDS2C)(0), // 0: msgid.MsgIDS2C
}
var file_msg_id_s2c_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_id_s2c_proto_init() }
func file_msg_id_s2c_proto_init() {
	if File_msg_id_s2c_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_id_s2c_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_id_s2c_proto_goTypes,
		DependencyIndexes: file_msg_id_s2c_proto_depIdxs,
		EnumInfos:         file_msg_id_s2c_proto_enumTypes,
	}.Build()
	File_msg_id_s2c_proto = out.File
	file_msg_id_s2c_proto_rawDesc = nil
	file_msg_id_s2c_proto_goTypes = nil
	file_msg_id_s2c_proto_depIdxs = nil
}
