// Code generated by tools/proto/build.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_id_c2s.proto

package msgid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client向Server发送消息
type MsgIDC2S int32

const (
	MsgIDC2S_C2SGateHandle    MsgIDC2S = 0
	MsgIDC2S_C2SInit          MsgIDC2S = 1
	MsgIDC2S_C2SAccountHandle MsgIDC2S = 100000
	MsgIDC2S_C2SLogin         MsgIDC2S = 100001
	MsgIDC2S_C2SBindAcc       MsgIDC2S = 100005
	MsgIDC2S_C2SGameHandle    MsgIDC2S = 200000
	MsgIDC2S_C2SClientReady   MsgIDC2S = 200001
	MsgIDC2S_C2SHeartBeat     MsgIDC2S = 200004
	MsgIDC2S_C2SWithoutRole   MsgIDC2S = 200006
)

// Enum value maps for MsgIDC2S.
var (
	MsgIDC2S_name = map[int32]string{
		0:      "C2SGateHandle",
		1:      "C2SInit",
		100000: "C2SAccountHandle",
		100001: "C2SLogin",
		100005: "C2SBindAcc",
		200000: "C2SGameHandle",
		200001: "C2SClientReady",
		200004: "C2SHeartBeat",
		200006: "C2SWithoutRole",
	}
	MsgIDC2S_value = map[string]int32{
		"C2SGateHandle":    0,
		"C2SInit":          1,
		"C2SAccountHandle": 100000,
		"C2SLogin":         100001,
		"C2SBindAcc":       100005,
		"C2SGameHandle":    200000,
		"C2SClientReady":   200001,
		"C2SHeartBeat":     200004,
		"C2SWithoutRole":   200006,
	}
)

func (x MsgIDC2S) Enum() *MsgIDC2S {
	p := new(MsgIDC2S)
	*p = x
	return p
}

func (x MsgIDC2S) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgIDC2S) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_id_c2s_proto_enumTypes[0].Descriptor()
}

func (MsgIDC2S) Type() protoreflect.EnumType {
	return &file_msg_id_c2s_proto_enumTypes[0]
}

func (x MsgIDC2S) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgIDC2S.Descriptor instead.
func (MsgIDC2S) EnumDescriptor() ([]byte, []int) {
	return file_msg_id_c2s_proto_rawDescGZIP(), []int{0}
}

var File_msg_id_c2s_proto protoreflect.FileDescriptor

var file_msg_id_c2s_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x5f, 0x63, 0x32, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x2a, 0xb9, 0x01, 0x0a, 0x08, 0x4d, 0x73,
	0x67, 0x49, 0x44, 0x43, 0x32, 0x53, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x47, 0x61, 0x74,
	0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x32, 0x53,
	0x49, 0x6e, 0x69, 0x74, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x10, 0xa0, 0x8d, 0x06, 0x12, 0x0e,
	0x0a, 0x08, 0x43, 0x32, 0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0xa1, 0x8d, 0x06, 0x12, 0x10,
	0x0a, 0x0a, 0x43, 0x32, 0x53, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x10, 0xa5, 0x8d, 0x06,
	0x12, 0x13, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x10, 0xc0, 0x9a, 0x0c, 0x12, 0x14, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0xc1, 0x9a, 0x0c, 0x12, 0x12, 0x0a, 0x0c, 0x43,
	0x32, 0x53, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0xc4, 0x9a, 0x0c, 0x12,
	0x14, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x6c,
	0x65, 0x10, 0xc6, 0x9a, 0x0c, 0x42, 0x0b, 0x48, 0x03, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x73, 0x67,
	0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_id_c2s_proto_rawDescOnce sync.Once
	file_msg_id_c2s_proto_rawDescData = file_msg_id_c2s_proto_rawDesc
)

func file_msg_id_c2s_proto_rawDescGZIP() []byte {
	file_msg_id_c2s_proto_rawDescOnce.Do(func() {
		file_msg_id_c2s_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_id_c2s_proto_rawDescData)
	})
	return file_msg_id_c2s_proto_rawDescData
}

var file_msg_id_c2s_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_id_c2s_proto_goTypes = []interface{}{
	(MsgIDC2S)(0), // 0: msgid.MsgIDC2S
}
var file_msg_id_c2s_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_id_c2s_proto_init() }
func file_msg_id_c2s_proto_init() {
	if File_msg_id_c2s_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_id_c2s_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_id_c2s_proto_goTypes,
		DependencyIndexes: file_msg_id_c2s_proto_depIdxs,
		EnumInfos:         file_msg_id_c2s_proto_enumTypes,
	}.Build()
	File_msg_id_c2s_proto = out.File
	file_msg_id_c2s_proto_rawDesc = nil
	file_msg_id_c2s_proto_goTypes = nil
	file_msg_id_c2s_proto_depIdxs = nil
}
