// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EPlatType int32

const (
	EPlatType_EPT_And EPlatType = 0 //安卓
	EPlatType_EPT_IOS EPlatType = 1 //苹果
	EPlatType_EPT_Web EPlatType = 2 //网页
)

// Enum value maps for EPlatType.
var (
	EPlatType_name = map[int32]string{
		0: "EPT_And",
		1: "EPT_IOS",
		2: "EPT_Web",
	}
	EPlatType_value = map[string]int32{
		"EPT_And": 0,
		"EPT_IOS": 1,
		"EPT_Web": 2,
	}
)

func (x EPlatType) Enum() *EPlatType {
	p := new(EPlatType)
	*p = x
	return p
}

func (x EPlatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPlatType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[0].Descriptor()
}

func (EPlatType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[0]
}

func (x EPlatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPlatType.Descriptor instead.
func (EPlatType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{0}
}

type ELanguage int32

const (
	ELanguage_SimplifiedChinese  ELanguage = 0  //简体中文
	ELanguage_TraditionalChinese ELanguage = 1  //繁体中文
	ELanguage_English            ELanguage = 2  //英语
	ELanguage_Cantonese          ELanguage = 3  //粤语
	ELanguage_ClassicalChinese   ELanguage = 4  //文言文
	ELanguage_Japanese           ELanguage = 5  //日语
	ELanguage_Korean             ELanguage = 6  //韩语
	ELanguage_French             ELanguage = 7  //法语
	ELanguage_Spanish            ELanguage = 8  //西班牙语
	ELanguage_Thai               ELanguage = 9  //泰语
	ELanguage_Arabic             ELanguage = 10 //阿拉伯语
	ELanguage_Russian            ELanguage = 11 //俄语
	ELanguage_Portuguese         ELanguage = 12 //葡萄牙语
	ELanguage_German             ELanguage = 13 //德语
	ELanguage_Italian            ELanguage = 14 //意大利语
	ELanguage_Greek              ELanguage = 15 //希腊语
	ELanguage_Dutch              ELanguage = 16 //荷兰语
	ELanguage_Polish             ELanguage = 17 //波兰语
	ELanguage_Bulgarian          ELanguage = 18 //保加利亚语
	ELanguage_Estonian           ELanguage = 19 //爱沙尼亚语
	ELanguage_Danish             ELanguage = 20 //丹麦语
	ELanguage_Finnish            ELanguage = 21 //芬兰语
	ELanguage_Czech              ELanguage = 22 //捷克语
	ELanguage_Romanian           ELanguage = 23 //罗马尼亚语
	ELanguage_Slovenia           ELanguage = 24 //斯洛文尼亚语
	ELanguage_Swedish            ELanguage = 25 //瑞典语
	ELanguage_Hungarian          ELanguage = 26 //匈牙利语
	ELanguage_Vietnamese         ELanguage = 27 //越南语
	ELanguage_ESL_AUTO           ELanguage = 28 //自动检测
	ELanguage_LanguageNum        ELanguage = 29 //语言数量
)

// Enum value maps for ELanguage.
var (
	ELanguage_name = map[int32]string{
		0:  "SimplifiedChinese",
		1:  "TraditionalChinese",
		2:  "English",
		3:  "Cantonese",
		4:  "ClassicalChinese",
		5:  "Japanese",
		6:  "Korean",
		7:  "French",
		8:  "Spanish",
		9:  "Thai",
		10: "Arabic",
		11: "Russian",
		12: "Portuguese",
		13: "German",
		14: "Italian",
		15: "Greek",
		16: "Dutch",
		17: "Polish",
		18: "Bulgarian",
		19: "Estonian",
		20: "Danish",
		21: "Finnish",
		22: "Czech",
		23: "Romanian",
		24: "Slovenia",
		25: "Swedish",
		26: "Hungarian",
		27: "Vietnamese",
		28: "ESL_AUTO",
		29: "LanguageNum",
	}
	ELanguage_value = map[string]int32{
		"SimplifiedChinese":  0,
		"TraditionalChinese": 1,
		"English":            2,
		"Cantonese":          3,
		"ClassicalChinese":   4,
		"Japanese":           5,
		"Korean":             6,
		"French":             7,
		"Spanish":            8,
		"Thai":               9,
		"Arabic":             10,
		"Russian":            11,
		"Portuguese":         12,
		"German":             13,
		"Italian":            14,
		"Greek":              15,
		"Dutch":              16,
		"Polish":             17,
		"Bulgarian":          18,
		"Estonian":           19,
		"Danish":             20,
		"Finnish":            21,
		"Czech":              22,
		"Romanian":           23,
		"Slovenia":           24,
		"Swedish":            25,
		"Hungarian":          26,
		"Vietnamese":         27,
		"ESL_AUTO":           28,
		"LanguageNum":        29,
	}
)

func (x ELanguage) Enum() *ELanguage {
	p := new(ELanguage)
	*p = x
	return p
}

func (x ELanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ELanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[1].Descriptor()
}

func (ELanguage) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[1]
}

func (x ELanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ELanguage.Descriptor instead.
func (ELanguage) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{1}
}

type EGoodsType int32

const (
	EGoodsType_EGT_None      EGoodsType = 0
	EGoodsType_EGT_Numerical EGoodsType = 1 //数值道具
	EGoodsType_EGT_Normal    EGoodsType = 2 //常规道具
)

// Enum value maps for EGoodsType.
var (
	EGoodsType_name = map[int32]string{
		0: "EGT_None",
		1: "EGT_Numerical",
		2: "EGT_Normal",
	}
	EGoodsType_value = map[string]int32{
		"EGT_None":      0,
		"EGT_Numerical": 1,
		"EGT_Normal":    2,
	}
)

func (x EGoodsType) Enum() *EGoodsType {
	p := new(EGoodsType)
	*p = x
	return p
}

func (x EGoodsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGoodsType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[2].Descriptor()
}

func (EGoodsType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[2]
}

func (x EGoodsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EGoodsType.Descriptor instead.
func (EGoodsType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{2}
}

// --------------奖励-----------------
type EPrizeType int32

const (
	EPrizeType_None   EPrizeType = 0
	EPrizeType_Card   EPrizeType = 1 //卡
	EPrizeType_Bottle EPrizeType = 2 //漂流瓶
	EPrizeType_Good   EPrizeType = 3 //物品
)

// Enum value maps for EPrizeType.
var (
	EPrizeType_name = map[int32]string{
		0: "None",
		1: "Card",
		2: "Bottle",
		3: "Good",
	}
	EPrizeType_value = map[string]int32{
		"None":   0,
		"Card":   1,
		"Bottle": 2,
		"Good":   3,
	}
)

func (x EPrizeType) Enum() *EPrizeType {
	p := new(EPrizeType)
	*p = x
	return p
}

func (x EPrizeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPrizeType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[3].Descriptor()
}

func (EPrizeType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[3]
}

func (x EPrizeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPrizeType.Descriptor instead.
func (EPrizeType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{3}
}

// sdk
type ESdkNumber int32

const (
	ESdkNumber_GuestOverSeas ESdkNumber = 0 //游客
	ESdkNumber_Facebook      ESdkNumber = 1 //fackbook
	ESdkNumber_Google        ESdkNumber = 2 //原生google
	ESdkNumber_Apple         ESdkNumber = 3 //原生苹果
	ESdkNumber_QuikSDK       ESdkNumber = 4 //国服quickSDK
	ESdkNumber_QKGoogle      ESdkNumber = 5 //quikSDK 海外google
	ESdkNumber_QKApp         ESdkNumber = 6 //quikSDK 海外苹果
)

// Enum value maps for ESdkNumber.
var (
	ESdkNumber_name = map[int32]string{
		0: "GuestOverSeas",
		1: "Facebook",
		2: "Google",
		3: "Apple",
		4: "QuikSDK",
		5: "QKGoogle",
		6: "QKApp",
	}
	ESdkNumber_value = map[string]int32{
		"GuestOverSeas": 0,
		"Facebook":      1,
		"Google":        2,
		"Apple":         3,
		"QuikSDK":       4,
		"QKGoogle":      5,
		"QKApp":         6,
	}
)

func (x ESdkNumber) Enum() *ESdkNumber {
	p := new(ESdkNumber)
	*p = x
	return p
}

func (x ESdkNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESdkNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[4].Descriptor()
}

func (ESdkNumber) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[4]
}

func (x ESdkNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESdkNumber.Descriptor instead.
func (ESdkNumber) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{4}
}

type TypeComp int32

const (
	TypeComp_TCBase         TypeComp = 0
	TypeComp_TCExample      TypeComp = 1
	TypeComp_TCEmptyExample TypeComp = 2
)

// Enum value maps for TypeComp.
var (
	TypeComp_name = map[int32]string{
		0: "TCBase",
		1: "TCExample",
		2: "TCEmptyExample",
	}
	TypeComp_value = map[string]int32{
		"TCBase":         0,
		"TCExample":      1,
		"TCEmptyExample": 2,
	}
)

func (x TypeComp) Enum() *TypeComp {
	p := new(TypeComp)
	*p = x
	return p
}

func (x TypeComp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeComp) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[5].Descriptor()
}

func (TypeComp) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[5]
}

func (x TypeComp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeComp.Descriptor instead.
func (TypeComp) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{5}
}

// 一些公共结构
type MsgInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"zigzag32,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgInt) Reset() {
	*x = MsgInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInt) ProtoMessage() {}

func (x *MsgInt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInt.ProtoReflect.Descriptor instead.
func (*MsgInt) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{0}
}

func (x *MsgInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgUint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgUint) Reset() {
	*x = MsgUint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUint) ProtoMessage() {}

func (x *MsgUint) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUint.ProtoReflect.Descriptor instead.
func (*MsgUint) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{1}
}

func (x *MsgUint) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgBigInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"zigzag64,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgBigInt) Reset() {
	*x = MsgBigInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBigInt) ProtoMessage() {}

func (x *MsgBigInt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBigInt.ProtoReflect.Descriptor instead.
func (*MsgBigInt) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{2}
}

func (x *MsgBigInt) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgBigUInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgBigUInt) Reset() {
	*x = MsgBigUInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBigUInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBigUInt) ProtoMessage() {}

func (x *MsgBigUInt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBigUInt.ProtoReflect.Descriptor instead.
func (*MsgBigUInt) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{3}
}

func (x *MsgBigUInt) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgStr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgStr) Reset() {
	*x = MsgStr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStr) ProtoMessage() {}

func (x *MsgStr) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStr.ProtoReflect.Descriptor instead.
func (*MsgStr) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{4}
}

func (x *MsgStr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MsgBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgBool) Reset() {
	*x = MsgBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBool) ProtoMessage() {}

func (x *MsgBool) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBool.ProtoReflect.Descriptor instead.
func (*MsgBool) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{5}
}

func (x *MsgBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type MsgFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgFloat) Reset() {
	*x = MsgFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFloat) ProtoMessage() {}

func (x *MsgFloat) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFloat.ProtoReflect.Descriptor instead.
func (*MsgFloat) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{6}
}

func (x *MsgFloat) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int32 `protobuf:"zigzag32,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value int32 `protobuf:"zigzag32,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgKeyValue) Reset() {
	*x = MsgKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgKeyValue) ProtoMessage() {}

func (x *MsgKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgKeyValue.ProtoReflect.Descriptor instead.
func (*MsgKeyValue) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{7}
}

func (x *MsgKeyValue) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *MsgKeyValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgKeyValueU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgKeyValueU) Reset() {
	*x = MsgKeyValueU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgKeyValueU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgKeyValueU) ProtoMessage() {}

func (x *MsgKeyValueU) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgKeyValueU.ProtoReflect.Descriptor instead.
func (*MsgKeyValueU) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{8}
}

func (x *MsgKeyValueU) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *MsgKeyValueU) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgKVGuidValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid  uint64 `protobuf:"varint,1,opt,name=Guid,proto3" json:"Guid,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgKVGuidValue) Reset() {
	*x = MsgKVGuidValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgKVGuidValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgKVGuidValue) ProtoMessage() {}

func (x *MsgKVGuidValue) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgKVGuidValue.ProtoReflect.Descriptor instead.
func (*MsgKVGuidValue) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{9}
}

func (x *MsgKVGuidValue) GetGuid() uint64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *MsgKVGuidValue) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MsgStrKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgStrKeyValue) Reset() {
	*x = MsgStrKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStrKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStrKeyValue) ProtoMessage() {}

func (x *MsgStrKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStrKeyValue.ProtoReflect.Descriptor instead.
func (*MsgStrKeyValue) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{10}
}

func (x *MsgStrKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MsgStrKeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MsgStrKeyValueArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value []string `protobuf:"bytes,2,rep,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgStrKeyValueArray) Reset() {
	*x = MsgStrKeyValueArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStrKeyValueArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStrKeyValueArray) ProtoMessage() {}

func (x *MsgStrKeyValueArray) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStrKeyValueArray.ProtoReflect.Descriptor instead.
func (*MsgStrKeyValueArray) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{11}
}

func (x *MsgStrKeyValueArray) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MsgStrKeyValueArray) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type MsgBoolKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int32 `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value bool  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgBoolKeyValue) Reset() {
	*x = MsgBoolKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBoolKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBoolKeyValue) ProtoMessage() {}

func (x *MsgBoolKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBoolKeyValue.ProtoReflect.Descriptor instead.
func (*MsgBoolKeyValue) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{12}
}

func (x *MsgBoolKeyValue) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *MsgBoolKeyValue) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type MsgUintBoolMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value map[uint32]bool `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *MsgUintBoolMap) Reset() {
	*x = MsgUintBoolMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUintBoolMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUintBoolMap) ProtoMessage() {}

func (x *MsgUintBoolMap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUintBoolMap.ProtoReflect.Descriptor instead.
func (*MsgUintBoolMap) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{13}
}

func (x *MsgUintBoolMap) GetValue() map[uint32]bool {
	if x != nil {
		return x.Value
	}
	return nil
}

type MsgIntArrary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []int32 `protobuf:"zigzag32,1,rep,packed,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgIntArrary) Reset() {
	*x = MsgIntArrary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgIntArrary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgIntArrary) ProtoMessage() {}

func (x *MsgIntArrary) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgIntArrary.ProtoReflect.Descriptor instead.
func (*MsgIntArrary) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{14}
}

func (x *MsgIntArrary) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type MsgUintArrary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []uint32 `protobuf:"varint,1,rep,packed,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgUintArrary) Reset() {
	*x = MsgUintArrary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUintArrary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUintArrary) ProtoMessage() {}

func (x *MsgUintArrary) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUintArrary.ProtoReflect.Descriptor instead.
func (*MsgUintArrary) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{15}
}

func (x *MsgUintArrary) GetValue() []uint32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type MsgUint64Arrary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []uint64 `protobuf:"varint,1,rep,packed,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgUint64Arrary) Reset() {
	*x = MsgUint64Arrary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUint64Arrary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUint64Arrary) ProtoMessage() {}

func (x *MsgUint64Arrary) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUint64Arrary.ProtoReflect.Descriptor instead.
func (*MsgUint64Arrary) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{16}
}

func (x *MsgUint64Arrary) GetValue() []uint64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type MsgStringArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MsgStringArray) Reset() {
	*x = MsgStringArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStringArray) ProtoMessage() {}

func (x *MsgStringArray) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStringArray.ProtoReflect.Descriptor instead.
func (*MsgStringArray) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{17}
}

func (x *MsgStringArray) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type MsgMapInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs map[int32]int32 `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty" protobuf_key:"zigzag32,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
}

func (x *MsgMapInt) Reset() {
	*x = MsgMapInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMapInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMapInt) ProtoMessage() {}

func (x *MsgMapInt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMapInt.ProtoReflect.Descriptor instead.
func (*MsgMapInt) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{18}
}

func (x *MsgMapInt) GetPairs() map[int32]int32 {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type MsgMapU64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs map[uint64]uint64 `protobuf:"bytes,1,rep,name=Pairs,proto3" json:"Pairs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *MsgMapU64) Reset() {
	*x = MsgMapU64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMapU64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMapU64) ProtoMessage() {}

func (x *MsgMapU64) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMapU64.ProtoReflect.Descriptor instead.
func (*MsgMapU64) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{19}
}

func (x *MsgMapU64) GetPairs() map[uint64]uint64 {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type MsgKeyValueArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kv []*MsgKeyValue `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty"`
}

func (x *MsgKeyValueArray) Reset() {
	*x = MsgKeyValueArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgKeyValueArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgKeyValueArray) ProtoMessage() {}

func (x *MsgKeyValueArray) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgKeyValueArray.ProtoReflect.Descriptor instead.
func (*MsgKeyValueArray) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{20}
}

func (x *MsgKeyValueArray) GetKv() []*MsgKeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

type MsgPairStringInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=Str,proto3" json:"Str,omitempty"`
	Num int32  `protobuf:"zigzag32,2,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *MsgPairStringInt) Reset() {
	*x = MsgPairStringInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPairStringInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPairStringInt) ProtoMessage() {}

func (x *MsgPairStringInt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPairStringInt.ProtoReflect.Descriptor instead.
func (*MsgPairStringInt) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{21}
}

func (x *MsgPairStringInt) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *MsgPairStringInt) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type MsgFloatInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntV   int64   `protobuf:"zigzag64,1,opt,name=IntV,proto3" json:"IntV,omitempty"`
	FloatV float64 `protobuf:"fixed64,2,opt,name=FloatV,proto3" json:"FloatV,omitempty"`
}

func (x *MsgFloatInt) Reset() {
	*x = MsgFloatInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFloatInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFloatInt) ProtoMessage() {}

func (x *MsgFloatInt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFloatInt.ProtoReflect.Descriptor instead.
func (*MsgFloatInt) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{22}
}

func (x *MsgFloatInt) GetIntV() int64 {
	if x != nil {
		return x.IntV
	}
	return 0
}

func (x *MsgFloatInt) GetFloatV() float64 {
	if x != nil {
		return x.FloatV
	}
	return 0
}

type PrizeItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    EPrizeType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.EPrizeType" json:"Type,omitempty"` //物品类型
	Oriname string     `protobuf:"bytes,2,opt,name=Oriname,proto3" json:"Oriname,omitempty"`               //物品原始名
	Count   int64      `protobuf:"zigzag64,3,opt,name=Count,proto3" json:"Count,omitempty"`                //物品数量
	Rate    float32    `protobuf:"fixed32,4,opt,name=Rate,proto3" json:"Rate,omitempty"`                   //倍率
	Extra   []int32    `protobuf:"zigzag32,5,rep,packed,name=Extra,proto3" json:"Extra,omitempty"`         //额外属性(与具体功能有关)
}

func (x *PrizeItem) Reset() {
	*x = PrizeItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrizeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizeItem) ProtoMessage() {}

func (x *PrizeItem) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizeItem.ProtoReflect.Descriptor instead.
func (*PrizeItem) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{23}
}

func (x *PrizeItem) GetType() EPrizeType {
	if x != nil {
		return x.Type
	}
	return EPrizeType_None
}

func (x *PrizeItem) GetOriname() string {
	if x != nil {
		return x.Oriname
	}
	return ""
}

func (x *PrizeItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PrizeItem) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *PrizeItem) GetExtra() []int32 {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PrizeItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PrizeItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *PrizeItems) Reset() {
	*x = PrizeItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrizeItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizeItems) ProtoMessage() {}

func (x *PrizeItems) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizeItems.ProtoReflect.Descriptor instead.
func (*PrizeItems) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{24}
}

func (x *PrizeItems) GetItems() []*PrizeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PrizePoolData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    EPrizeType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.EPrizeType" json:"Type,omitempty"` //物品类型
	Oriname string     `protobuf:"bytes,2,opt,name=Oriname,proto3" json:"Oriname,omitempty"`               //物品原始名
	Count   int64      `protobuf:"zigzag64,3,opt,name=Count,proto3" json:"Count,omitempty"`                //物品数量
	TeShu   uint32     `protobuf:"varint,4,opt,name=TeShu,proto3" json:"TeShu,omitempty"`                  //特殊
	Ex      uint32     `protobuf:"varint,5,opt,name=Ex,proto3" json:"Ex,omitempty"`                        //特殊
	Rand    uint32     `protobuf:"varint,6,opt,name=Rand,proto3" json:"Rand,omitempty"`                    //特殊
}

func (x *PrizePoolData) Reset() {
	*x = PrizePoolData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrizePoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizePoolData) ProtoMessage() {}

func (x *PrizePoolData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizePoolData.ProtoReflect.Descriptor instead.
func (*PrizePoolData) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{25}
}

func (x *PrizePoolData) GetType() EPrizeType {
	if x != nil {
		return x.Type
	}
	return EPrizeType_None
}

func (x *PrizePoolData) GetOriname() string {
	if x != nil {
		return x.Oriname
	}
	return ""
}

func (x *PrizePoolData) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PrizePoolData) GetTeShu() uint32 {
	if x != nil {
		return x.TeShu
	}
	return 0
}

func (x *PrizePoolData) GetEx() uint32 {
	if x != nil {
		return x.Ex
	}
	return 0
}

func (x *PrizePoolData) GetRand() uint32 {
	if x != nil {
		return x.Rand
	}
	return 0
}

var File_msg_common_proto protoreflect.FileDescriptor

var file_msg_common_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1e, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x55, 0x69, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x42, 0x69,
	0x67, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x4d, 0x73,
	0x67, 0x42, 0x69, 0x67, 0x55, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e,
	0x0a, 0x06, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x20, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x35, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x11, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x55, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x3a, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x4b, 0x56, 0x47, 0x75, 0x69, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x47, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x0e,
	0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72,
	0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x6f, 0x6c,
	0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x7f, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x55, 0x69, 0x6e, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x4d,
	0x61, 0x70, 0x12, 0x33, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x69, 0x6e, 0x74, 0x42, 0x6f,
	0x6f, 0x6c, 0x4d, 0x61, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x24, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x11,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x55, 0x69,
	0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27,
	0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x75, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x05,
	0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x1a, 0x38, 0x0a, 0x0a,
	0x50, 0x61, 0x69, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x75, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x4d, 0x61, 0x70,
	0x55, 0x36, 0x34, 0x12, 0x2e, 0x0a, 0x05, 0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x61, 0x70, 0x55, 0x36,
	0x34, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x50, 0x61,
	0x69, 0x72, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x61, 0x69, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x33, 0x0a,
	0x10, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x1f, 0x0a, 0x02, 0x6b, 0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02,
	0x6b, 0x76, 0x22, 0x36, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x69, 0x72, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x74, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x39, 0x0a, 0x0b, 0x4d, 0x73,
	0x67, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x74,
	0x56, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x04, 0x49, 0x6e, 0x74, 0x56, 0x12, 0x16, 0x0a,
	0x06, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x56, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x69, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x69, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x11, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x22, 0x31, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x23, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x6f,
	0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x50, 0x72, 0x69, 0x7a, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x69, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x69,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x65,
	0x53, 0x68, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54, 0x65, 0x53, 0x68, 0x75,
	0x12, 0x0e, 0x0a, 0x02, 0x45, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x45, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x52, 0x61, 0x6e, 0x64, 0x2a, 0x32, 0x0a, 0x09, 0x45, 0x50, 0x6c, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x50, 0x54, 0x5f, 0x41, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x50, 0x54, 0x5f, 0x49, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45,
	0x50, 0x54, 0x5f, 0x57, 0x65, 0x62, 0x10, 0x02, 0x2a, 0xb5, 0x03, 0x0a, 0x09, 0x45, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x43, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x54, 0x72, 0x61, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x68, 0x69, 0x6e,
	0x65, 0x73, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x65, 0x10,
	0x03, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x65, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x61, 0x70, 0x61, 0x6e,
	0x65, 0x73, 0x65, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x6f, 0x72, 0x65, 0x61, 0x6e, 0x10,
	0x06, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x72, 0x65, 0x6e, 0x63, 0x68, 0x10, 0x07, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x70, 0x61, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x68,
	0x61, 0x69, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x72, 0x61, 0x62, 0x69, 0x63, 0x10, 0x0a,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x73, 0x73, 0x69, 0x61, 0x6e, 0x10, 0x0b, 0x12, 0x0e, 0x0a,
	0x0a, 0x50, 0x6f, 0x72, 0x74, 0x75, 0x67, 0x75, 0x65, 0x73, 0x65, 0x10, 0x0c, 0x12, 0x0a, 0x0a,
	0x06, 0x47, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x10, 0x0d, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x74, 0x61,
	0x6c, 0x69, 0x61, 0x6e, 0x10, 0x0e, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6b, 0x10,
	0x0f, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x75, 0x74, 0x63, 0x68, 0x10, 0x10, 0x12, 0x0a, 0x0a, 0x06,
	0x50, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x10, 0x11, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x75, 0x6c, 0x67,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x10, 0x12, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x73, 0x74, 0x6f, 0x6e,
	0x69, 0x61, 0x6e, 0x10, 0x13, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x61, 0x6e, 0x69, 0x73, 0x68, 0x10,
	0x14, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x15, 0x12, 0x09,
	0x0a, 0x05, 0x43, 0x7a, 0x65, 0x63, 0x68, 0x10, 0x16, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x6f, 0x6d,
	0x61, 0x6e, 0x69, 0x61, 0x6e, 0x10, 0x17, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x6c, 0x6f, 0x76, 0x65,
	0x6e, 0x69, 0x61, 0x10, 0x18, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x77, 0x65, 0x64, 0x69, 0x73, 0x68,
	0x10, 0x19, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x75, 0x6e, 0x67, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x10,
	0x1a, 0x12, 0x0e, 0x0a, 0x0a, 0x56, 0x69, 0x65, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x10,
	0x1b, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x53, 0x4c, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x1c, 0x12,
	0x0f, 0x0a, 0x0b, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x10, 0x1d,
	0x2a, 0x3d, 0x0a, 0x0a, 0x45, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x45, 0x47, 0x54, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x45, 0x47, 0x54, 0x5f, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x45, 0x47, 0x54, 0x5f, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x02, 0x2a,
	0x36, 0x0a, 0x0a, 0x45, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x47, 0x6f, 0x6f, 0x64, 0x10, 0x03, 0x2a, 0x6a, 0x0a, 0x0a, 0x45, 0x53, 0x64, 0x6b, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x61, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65,
	0x62, 0x6f, 0x6f, 0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x51, 0x75, 0x69, 0x6b, 0x53, 0x44, 0x4b, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x51, 0x4b,
	0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x4b, 0x41, 0x70,
	0x70, 0x10, 0x06, 0x2a, 0x39, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x12,
	0x0a, 0x0a, 0x06, 0x54, 0x43, 0x42, 0x61, 0x73, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x43, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x43,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10, 0x02, 0x42, 0x08,
	0x48, 0x03, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_common_proto_rawDescOnce sync.Once
	file_msg_common_proto_rawDescData = file_msg_common_proto_rawDesc
)

func file_msg_common_proto_rawDescGZIP() []byte {
	file_msg_common_proto_rawDescOnce.Do(func() {
		file_msg_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_common_proto_rawDescData)
	})
	return file_msg_common_proto_rawDescData
}

var file_msg_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_msg_common_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_msg_common_proto_goTypes = []interface{}{
	(EPlatType)(0),              // 0: pb.EPlatType
	(ELanguage)(0),              // 1: pb.ELanguage
	(EGoodsType)(0),             // 2: pb.EGoodsType
	(EPrizeType)(0),             // 3: pb.EPrizeType
	(ESdkNumber)(0),             // 4: pb.ESdkNumber
	(TypeComp)(0),               // 5: pb.TypeComp
	(*MsgInt)(nil),              // 6: pb.MsgInt
	(*MsgUint)(nil),             // 7: pb.MsgUint
	(*MsgBigInt)(nil),           // 8: pb.MsgBigInt
	(*MsgBigUInt)(nil),          // 9: pb.MsgBigUInt
	(*MsgStr)(nil),              // 10: pb.MsgStr
	(*MsgBool)(nil),             // 11: pb.MsgBool
	(*MsgFloat)(nil),            // 12: pb.MsgFloat
	(*MsgKeyValue)(nil),         // 13: pb.MsgKeyValue
	(*MsgKeyValueU)(nil),        // 14: pb.MsgKeyValueU
	(*MsgKVGuidValue)(nil),      // 15: pb.MsgKVGuidValue
	(*MsgStrKeyValue)(nil),      // 16: pb.MsgStrKeyValue
	(*MsgStrKeyValueArray)(nil), // 17: pb.MsgStrKeyValueArray
	(*MsgBoolKeyValue)(nil),     // 18: pb.MsgBoolKeyValue
	(*MsgUintBoolMap)(nil),      // 19: pb.MsgUintBoolMap
	(*MsgIntArrary)(nil),        // 20: pb.MsgIntArrary
	(*MsgUintArrary)(nil),       // 21: pb.MsgUintArrary
	(*MsgUint64Arrary)(nil),     // 22: pb.MsgUint64Arrary
	(*MsgStringArray)(nil),      // 23: pb.MsgStringArray
	(*MsgMapInt)(nil),           // 24: pb.MsgMapInt
	(*MsgMapU64)(nil),           // 25: pb.MsgMapU64
	(*MsgKeyValueArray)(nil),    // 26: pb.MsgKeyValueArray
	(*MsgPairStringInt)(nil),    // 27: pb.MsgPairStringInt
	(*MsgFloatInt)(nil),         // 28: pb.MsgFloatInt
	(*PrizeItem)(nil),           // 29: pb.PrizeItem
	(*PrizeItems)(nil),          // 30: pb.PrizeItems
	(*PrizePoolData)(nil),       // 31: pb.PrizePoolData
	nil,                         // 32: pb.MsgUintBoolMap.ValueEntry
	nil,                         // 33: pb.MsgMapInt.PairsEntry
	nil,                         // 34: pb.MsgMapU64.PairsEntry
}
var file_msg_common_proto_depIdxs = []int32{
	32, // 0: pb.MsgUintBoolMap.Value:type_name -> pb.MsgUintBoolMap.ValueEntry
	33, // 1: pb.MsgMapInt.pairs:type_name -> pb.MsgMapInt.PairsEntry
	34, // 2: pb.MsgMapU64.Pairs:type_name -> pb.MsgMapU64.PairsEntry
	13, // 3: pb.MsgKeyValueArray.kv:type_name -> pb.MsgKeyValue
	3,  // 4: pb.PrizeItem.Type:type_name -> pb.EPrizeType
	29, // 5: pb.PrizeItems.Items:type_name -> pb.PrizeItem
	3,  // 6: pb.PrizePoolData.Type:type_name -> pb.EPrizeType
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_msg_common_proto_init() }
func file_msg_common_proto_init() {
	if File_msg_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBigInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBigUInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgKeyValueU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgKVGuidValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStrKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStrKeyValueArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBoolKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUintBoolMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgIntArrary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUintArrary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUint64Arrary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStringArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMapInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMapU64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgKeyValueArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPairStringInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFloatInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrizeItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrizeItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrizePoolData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_common_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_common_proto_goTypes,
		DependencyIndexes: file_msg_common_proto_depIdxs,
		EnumInfos:         file_msg_common_proto_enumTypes,
		MessageInfos:      file_msg_common_proto_msgTypes,
	}.Build()
	File_msg_common_proto = out.File
	file_msg_common_proto_rawDesc = nil
	file_msg_common_proto_goTypes = nil
	file_msg_common_proto_depIdxs = nil
}
