// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SrvService_SrvSrv_FullMethodName = "/pb.SrvService/SrvSrv"
)

// SrvServiceClient is the client API for SrvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvServiceClient interface {
	SrvSrv(ctx context.Context, opts ...grpc.CallOption) (SrvService_SrvSrvClient, error)
}

type srvServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvServiceClient(cc grpc.ClientConnInterface) SrvServiceClient {
	return &srvServiceClient{cc}
}

func (c *srvServiceClient) SrvSrv(ctx context.Context, opts ...grpc.CallOption) (SrvService_SrvSrvClient, error) {
	stream, err := c.cc.NewStream(ctx, &SrvService_ServiceDesc.Streams[0], SrvService_SrvSrv_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &srvServiceSrvSrvClient{stream}
	return x, nil
}

type SrvService_SrvSrvClient interface {
	Send(*SrvMsgs) error
	Recv() (*SrvMsgs, error)
	grpc.ClientStream
}

type srvServiceSrvSrvClient struct {
	grpc.ClientStream
}

func (x *srvServiceSrvSrvClient) Send(m *SrvMsgs) error {
	return x.ClientStream.SendMsg(m)
}

func (x *srvServiceSrvSrvClient) Recv() (*SrvMsgs, error) {
	m := new(SrvMsgs)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SrvServiceServer is the server API for SrvService service.
// All implementations must embed UnimplementedSrvServiceServer
// for forward compatibility
type SrvServiceServer interface {
	SrvSrv(SrvService_SrvSrvServer) error
	mustEmbedUnimplementedSrvServiceServer()
}

// UnimplementedSrvServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSrvServiceServer struct {
}

func (UnimplementedSrvServiceServer) SrvSrv(SrvService_SrvSrvServer) error {
	return status.Errorf(codes.Unimplemented, "method SrvSrv not implemented")
}
func (UnimplementedSrvServiceServer) mustEmbedUnimplementedSrvServiceServer() {}

// UnsafeSrvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvServiceServer will
// result in compilation errors.
type UnsafeSrvServiceServer interface {
	mustEmbedUnimplementedSrvServiceServer()
}

func RegisterSrvServiceServer(s grpc.ServiceRegistrar, srv SrvServiceServer) {
	s.RegisterService(&SrvService_ServiceDesc, srv)
}

func _SrvService_SrvSrv_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SrvServiceServer).SrvSrv(&srvServiceSrvSrvServer{stream})
}

type SrvService_SrvSrvServer interface {
	Send(*SrvMsgs) error
	Recv() (*SrvMsgs, error)
	grpc.ServerStream
}

type srvServiceSrvSrvServer struct {
	grpc.ServerStream
}

func (x *srvServiceSrvSrvServer) Send(m *SrvMsgs) error {
	return x.ServerStream.SendMsg(m)
}

func (x *srvServiceSrvSrvServer) Recv() (*SrvMsgs, error) {
	m := new(SrvMsgs)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SrvService_ServiceDesc is the grpc.ServiceDesc for SrvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SrvService",
	HandlerType: (*SrvServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SrvSrv",
			Handler:       _SrvService_SrvSrv_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
