// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_common.proto

//---------------说明---------------------------
//公用结构,
//----------------------------------------------

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Server int32

const (
	Server_Gateway Server = 0
	Server_Account Server = 1
	Server_Game    Server = 2
	Server_Center  Server = 3
	Server_Log     Server = 4
	Server_GM      Server = 20
	Server_Robot   Server = 21
	Server_Max     Server = 22
)

// Enum value maps for Server.
var (
	Server_name = map[int32]string{
		0:  "Gateway",
		1:  "Account",
		2:  "Game",
		3:  "Center",
		4:  "Log",
		20: "GM",
		21: "Robot",
		22: "Max",
	}
	Server_value = map[string]int32{
		"Gateway": 0,
		"Account": 1,
		"Game":    2,
		"Center":  3,
		"Log":     4,
		"GM":      20,
		"Robot":   21,
		"Max":     22,
	}
)

func (x Server) Enum() *Server {
	p := new(Server)
	*p = x
	return p
}

func (x Server) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Server) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[0].Descriptor()
}

func (Server) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[0]
}

func (x Server) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Server.Descriptor instead.
func (Server) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{0}
}

type EPlatType int32

const (
	EPlatType_EPT_And EPlatType = 0 //安卓
	EPlatType_EPT_IOS EPlatType = 1 //苹果
	EPlatType_EPT_Web EPlatType = 2 //网页
)

// Enum value maps for EPlatType.
var (
	EPlatType_name = map[int32]string{
		0: "EPT_And",
		1: "EPT_IOS",
		2: "EPT_Web",
	}
	EPlatType_value = map[string]int32{
		"EPT_And": 0,
		"EPT_IOS": 1,
		"EPT_Web": 2,
	}
)

func (x EPlatType) Enum() *EPlatType {
	p := new(EPlatType)
	*p = x
	return p
}

func (x EPlatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPlatType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[1].Descriptor()
}

func (EPlatType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[1]
}

func (x EPlatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPlatType.Descriptor instead.
func (EPlatType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{1}
}

// sdk
type SdkType int32

const (
	SdkType_Guest    SdkType = 0 //游客
	SdkType_Facebook SdkType = 1 //facebook
	SdkType_Google   SdkType = 2 //原生google
	SdkType_Apple    SdkType = 3 //原生苹果
)

// Enum value maps for SdkType.
var (
	SdkType_name = map[int32]string{
		0: "Guest",
		1: "Facebook",
		2: "Google",
		3: "Apple",
	}
	SdkType_value = map[string]int32{
		"Guest":    0,
		"Facebook": 1,
		"Google":   2,
		"Apple":    3,
	}
)

func (x SdkType) Enum() *SdkType {
	p := new(SdkType)
	*p = x
	return p
}

func (x SdkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdkType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[2].Descriptor()
}

func (SdkType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[2]
}

func (x SdkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdkType.Descriptor instead.
func (SdkType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{2}
}

type TypeComp int32

const (
	TypeComp_TCBase         TypeComp = 0
	TypeComp_TCExample      TypeComp = 1
	TypeComp_TCEmptyExample TypeComp = 2
	TypeComp_TCDebug        TypeComp = 3
	TypeComp_TCMax          TypeComp = 5 //保持最大
)

// Enum value maps for TypeComp.
var (
	TypeComp_name = map[int32]string{
		0: "TCBase",
		1: "TCExample",
		2: "TCEmptyExample",
		3: "TCDebug",
		5: "TCMax",
	}
	TypeComp_value = map[string]int32{
		"TCBase":         0,
		"TCExample":      1,
		"TCEmptyExample": 2,
		"TCDebug":        3,
		"TCMax":          5,
	}
)

func (x TypeComp) Enum() *TypeComp {
	p := new(TypeComp)
	*p = x
	return p
}

func (x TypeComp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeComp) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[3].Descriptor()
}

func (TypeComp) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[3]
}

func (x TypeComp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeComp.Descriptor instead.
func (TypeComp) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{3}
}

type ActorID int32

const (
	ActorID_IDExample  ActorID = 0
	ActorID_IDGlobal   ActorID = 1
	ActorID_IDAccBegin ActorID = 100000
)

// Enum value maps for ActorID.
var (
	ActorID_name = map[int32]string{
		0:      "IDExample",
		1:      "IDGlobal",
		100000: "IDAccBegin",
	}
	ActorID_value = map[string]int32{
		"IDExample":  0,
		"IDGlobal":   1,
		"IDAccBegin": 100000,
	}
)

func (x ActorID) Enum() *ActorID {
	p := new(ActorID)
	*p = x
	return p
}

func (x ActorID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[4].Descriptor()
}

func (ActorID) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[4]
}

func (x ActorID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorID.Descriptor instead.
func (ActorID) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{4}
}

var File_msg_common_proto protoreflect.FileDescriptor

var file_msg_common_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x5d, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x0b, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x61,
	0x6d, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x4d, 0x10,
	0x14, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x10, 0x15, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x61, 0x78, 0x10, 0x16, 0x2a, 0x32, 0x0a, 0x09, 0x45, 0x50, 0x6c, 0x61, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x50, 0x54, 0x5f, 0x41, 0x6e, 0x64, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x50, 0x54, 0x5f, 0x49, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x45, 0x50, 0x54, 0x5f, 0x57, 0x65, 0x62, 0x10, 0x02, 0x2a, 0x39, 0x0a, 0x07, 0x53, 0x64, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x75, 0x65, 0x73, 0x74, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70,
	0x6c, 0x65, 0x10, 0x03, 0x2a, 0x51, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x70,
	0x12, 0x0a, 0x0a, 0x06, 0x54, 0x43, 0x42, 0x61, 0x73, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x54, 0x43, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x54,
	0x43, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x43, 0x44, 0x65, 0x62, 0x75, 0x67, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x43, 0x4d, 0x61, 0x78, 0x10, 0x05, 0x2a, 0x38, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x44, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x44, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0a, 0x49, 0x44, 0x41, 0x63, 0x63, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x10, 0xa0, 0x8d,
	0x06, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_msg_common_proto_rawDescOnce sync.Once
	file_msg_common_proto_rawDescData = file_msg_common_proto_rawDesc
)

func file_msg_common_proto_rawDescGZIP() []byte {
	file_msg_common_proto_rawDescOnce.Do(func() {
		file_msg_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_common_proto_rawDescData)
	})
	return file_msg_common_proto_rawDescData
}

var file_msg_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_msg_common_proto_goTypes = []interface{}{
	(Server)(0),    // 0: pb.Server
	(EPlatType)(0), // 1: pb.EPlatType
	(SdkType)(0),   // 2: pb.SdkType
	(TypeComp)(0),  // 3: pb.TypeComp
	(ActorID)(0),   // 4: pb.ActorID
}
var file_msg_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_common_proto_init() }
func file_msg_common_proto_init() {
	if File_msg_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_common_proto_goTypes,
		DependencyIndexes: file_msg_common_proto_depIdxs,
		EnumInfos:         file_msg_common_proto_enumTypes,
	}.Build()
	File_msg_common_proto = out.File
	file_msg_common_proto_rawDesc = nil
	file_msg_common_proto_goTypes = nil
	file_msg_common_proto_depIdxs = nil
}
