//go:build ignore
// +build ignore

package main

//go:generate go run $GOFILE

import (
	"bytes"
	"go/format"
	"os"
	msgid2 "server/api/pb/msgid"
	"sort"
	"text/template"
)

const outFileName = "msg_helper.go"

type Node struct {
	Id    string
	Value string
}

func getNodes(msgIds map[int32]string) []*Node {
	var keys []int
	for k := range msgIds {
		keys = append(keys, int(k))
	}

	sort.Ints(keys)
	nodeSlice := make([]*Node, 0)
	for k := range keys {
		name := msgIds[int32(keys[k])]
		nodeSlice = append(nodeSlice, &Node{
			Id:    name,
			Value: name,
		})
	}
	return nodeSlice
}

func main() {
	tmpl, err := template.New("register").Parse(`// Code generated by tools/proto/generate_proto. DO NOT EDIT.
package pb

import (
	"reflect"
	"server/api/pb/msgid"
	"server/gmsg/gnet/pool"
)

var (
	{{range $i, $v := .S2C}} 
	Pool{{$v.Value}} = pool.NewMsgPool[{{$v.Value}}]()
	{{end}}
	{{range $i, $v := .S2S}} 
	Pool{{$v.Value}} = pool.NewMsgPool[{{$v.Value}}]()
	{{end}}
)

func registerAllC2SMsg()  {
	{{range $i, $v := .C2S}} registerC2SMsg(msgid.MsgIDC2S_{{$v.Id}}, &messageMeta{
		MessageType:reflect.TypeOf({{$v.Value}}{}),
		NewMessage: func() VTMessage { return &{{$v.Value}}{} },
	})
	
	{{end}}}
	
func registerAllS2CMsg()  {
	{{range $i, $v := .S2C}} registerS2CMsg(msgid.MsgIDS2C_{{$v.Id}}, &messageMeta{
		MessageType:reflect.TypeOf({{$v.Value}}{}),
		NewMessage: func() VTMessage { return &{{$v.Value}}{} },
	})
	
	{{end}}}

func registerAllS2SMsg()  {
	{{range $i, $v := .S2S}} registerS2SMsg(msgid.MsgIDS2S_{{$v.Id}}, &messageMeta{
		MessageType:reflect.TypeOf({{$v.Value}}{}),
		NewMessage: func() VTMessage { return &{{$v.Value}}{} },
	})
	
	{{end}}}`)

	if err != nil {
		panic(err)
	}

	type TempData struct {
		C2S []*Node
		S2C []*Node
		S2S []*Node
	}

	tmpData := &TempData{
		C2S: getNodes(msgid2.MsgIDC2S_name),
		S2C: getNodes(msgid2.MsgIDS2C_name),
		S2S: getNodes(msgid2.MsgIDS2S_name),
	}
	buff := bytes.NewBuffer(nil)
	if err := tmpl.Execute(buff, tmpData); err != nil {
		panic(err)
	}

	// fmt.Println(buff.String())
	// format code
	fineCode, err := format.Source(buff.Bytes())
	if err != nil {
		panic(err)
	}

	// write
	if err = os.WriteFile(outFileName, fineCode, os.ModePerm); err != nil {
		panic(err)
	}
}
