// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Server int32

const (
	Server_Gateway Server = 0
	Server_Account Server = 1
	Server_Game    Server = 2
	Server_Center  Server = 3
	Server_GM      Server = 20
	Server_Robot   Server = 21
)

// Enum value maps for Server.
var (
	Server_name = map[int32]string{
		0:  "Gateway",
		1:  "Account",
		2:  "Game",
		3:  "Center",
		20: "GM",
		21: "Robot",
	}
	Server_value = map[string]int32{
		"Gateway": 0,
		"Account": 1,
		"Game":    2,
		"Center":  3,
		"GM":      20,
		"Robot":   21,
	}
)

func (x Server) Enum() *Server {
	p := new(Server)
	*p = x
	return p
}

func (x Server) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Server) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[0].Descriptor()
}

func (Server) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[0]
}

func (x Server) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Server.Descriptor instead.
func (Server) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{0}
}

type EPlatType int32

const (
	EPlatType_EPT_And EPlatType = 0 //安卓
	EPlatType_EPT_IOS EPlatType = 1 //苹果
	EPlatType_EPT_Web EPlatType = 2 //网页
)

// Enum value maps for EPlatType.
var (
	EPlatType_name = map[int32]string{
		0: "EPT_And",
		1: "EPT_IOS",
		2: "EPT_Web",
	}
	EPlatType_value = map[string]int32{
		"EPT_And": 0,
		"EPT_IOS": 1,
		"EPT_Web": 2,
	}
)

func (x EPlatType) Enum() *EPlatType {
	p := new(EPlatType)
	*p = x
	return p
}

func (x EPlatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPlatType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[1].Descriptor()
}

func (EPlatType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[1]
}

func (x EPlatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPlatType.Descriptor instead.
func (EPlatType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{1}
}

// sdk
type ESdkNumber int32

const (
	ESdkNumber_Guest    ESdkNumber = 0 //游客
	ESdkNumber_Facebook ESdkNumber = 1 //facebook
	ESdkNumber_Google   ESdkNumber = 2 //原生google
	ESdkNumber_Apple    ESdkNumber = 3 //原生苹果
)

// Enum value maps for ESdkNumber.
var (
	ESdkNumber_name = map[int32]string{
		0: "Guest",
		1: "Facebook",
		2: "Google",
		3: "Apple",
	}
	ESdkNumber_value = map[string]int32{
		"Guest":    0,
		"Facebook": 1,
		"Google":   2,
		"Apple":    3,
	}
)

func (x ESdkNumber) Enum() *ESdkNumber {
	p := new(ESdkNumber)
	*p = x
	return p
}

func (x ESdkNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESdkNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[2].Descriptor()
}

func (ESdkNumber) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[2]
}

func (x ESdkNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESdkNumber.Descriptor instead.
func (ESdkNumber) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{2}
}

type TypeComp int32

const (
	TypeComp_TCBase         TypeComp = 0
	TypeComp_TCExample      TypeComp = 1
	TypeComp_TCEmptyExample TypeComp = 2
)

// Enum value maps for TypeComp.
var (
	TypeComp_name = map[int32]string{
		0: "TCBase",
		1: "TCExample",
		2: "TCEmptyExample",
	}
	TypeComp_value = map[string]int32{
		"TCBase":         0,
		"TCExample":      1,
		"TCEmptyExample": 2,
	}
)

func (x TypeComp) Enum() *TypeComp {
	p := new(TypeComp)
	*p = x
	return p
}

func (x TypeComp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeComp) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[3].Descriptor()
}

func (TypeComp) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[3]
}

func (x TypeComp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeComp.Descriptor instead.
func (TypeComp) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{3}
}

// --------------奖励-----------------
type EPrizeType int32

const (
	EPrizeType_None   EPrizeType = 0
	EPrizeType_Card   EPrizeType = 1 //卡
	EPrizeType_Bottle EPrizeType = 2 //漂流瓶
	EPrizeType_Good   EPrizeType = 3 //物品
)

// Enum value maps for EPrizeType.
var (
	EPrizeType_name = map[int32]string{
		0: "None",
		1: "Card",
		2: "Bottle",
		3: "Good",
	}
	EPrizeType_value = map[string]int32{
		"None":   0,
		"Card":   1,
		"Bottle": 2,
		"Good":   3,
	}
)

func (x EPrizeType) Enum() *EPrizeType {
	p := new(EPrizeType)
	*p = x
	return p
}

func (x EPrizeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPrizeType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_common_proto_enumTypes[4].Descriptor()
}

func (EPrizeType) Type() protoreflect.EnumType {
	return &file_msg_common_proto_enumTypes[4]
}

func (x EPrizeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPrizeType.Descriptor instead.
func (EPrizeType) EnumDescriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{4}
}

type PrizeItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    EPrizeType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.EPrizeType" json:"Type,omitempty"` //物品类型
	Oriname string     `protobuf:"bytes,2,opt,name=Oriname,proto3" json:"Oriname,omitempty"`               //物品原始名
	Count   int64      `protobuf:"zigzag64,3,opt,name=Count,proto3" json:"Count,omitempty"`                //物品数量
	Rate    float32    `protobuf:"fixed32,4,opt,name=Rate,proto3" json:"Rate,omitempty"`                   //倍率
	Extra   []int32    `protobuf:"zigzag32,5,rep,packed,name=Extra,proto3" json:"Extra,omitempty"`         //额外属性(与具体功能有关)
}

func (x *PrizeItem) Reset() {
	*x = PrizeItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrizeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizeItem) ProtoMessage() {}

func (x *PrizeItem) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizeItem.ProtoReflect.Descriptor instead.
func (*PrizeItem) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{0}
}

func (x *PrizeItem) GetType() EPrizeType {
	if x != nil {
		return x.Type
	}
	return EPrizeType_None
}

func (x *PrizeItem) GetOriname() string {
	if x != nil {
		return x.Oriname
	}
	return ""
}

func (x *PrizeItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PrizeItem) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *PrizeItem) GetExtra() []int32 {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PrizeItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PrizeItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *PrizeItems) Reset() {
	*x = PrizeItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrizeItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizeItems) ProtoMessage() {}

func (x *PrizeItems) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizeItems.ProtoReflect.Descriptor instead.
func (*PrizeItems) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{1}
}

func (x *PrizeItems) GetItems() []*PrizeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PrizePoolData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    EPrizeType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.EPrizeType" json:"Type,omitempty"` //物品类型
	Oriname string     `protobuf:"bytes,2,opt,name=Oriname,proto3" json:"Oriname,omitempty"`               //物品原始名
	Count   int64      `protobuf:"zigzag64,3,opt,name=Count,proto3" json:"Count,omitempty"`                //物品数量
	TeShu   uint32     `protobuf:"varint,4,opt,name=TeShu,proto3" json:"TeShu,omitempty"`                  //特殊
	Ex      uint32     `protobuf:"varint,5,opt,name=Ex,proto3" json:"Ex,omitempty"`                        //特殊
	Rand    uint32     `protobuf:"varint,6,opt,name=Rand,proto3" json:"Rand,omitempty"`                    //特殊
}

func (x *PrizePoolData) Reset() {
	*x = PrizePoolData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrizePoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizePoolData) ProtoMessage() {}

func (x *PrizePoolData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizePoolData.ProtoReflect.Descriptor instead.
func (*PrizePoolData) Descriptor() ([]byte, []int) {
	return file_msg_common_proto_rawDescGZIP(), []int{2}
}

func (x *PrizePoolData) GetType() EPrizeType {
	if x != nil {
		return x.Type
	}
	return EPrizeType_None
}

func (x *PrizePoolData) GetOriname() string {
	if x != nil {
		return x.Oriname
	}
	return ""
}

func (x *PrizePoolData) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PrizePoolData) GetTeShu() uint32 {
	if x != nil {
		return x.TeShu
	}
	return 0
}

func (x *PrizePoolData) GetEx() uint32 {
	if x != nil {
		return x.Ex
	}
	return 0
}

func (x *PrizePoolData) GetRand() uint32 {
	if x != nil {
		return x.Rand
	}
	return 0
}

var File_msg_common_proto protoreflect.FileDescriptor

var file_msg_common_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x7a, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x69, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x69, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x12, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x11, 0x52, 0x05, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x22, 0x31, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x23, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x50,
	0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x50, 0x72, 0x69, 0x7a,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x72, 0x69, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72,
	0x69, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x65, 0x53, 0x68, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54, 0x65, 0x53, 0x68,
	0x75, 0x12, 0x0e, 0x0a, 0x02, 0x45, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x45,
	0x78, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x52, 0x61, 0x6e, 0x64, 0x2a, 0x4b, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x0b, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x61, 0x6d,
	0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x03, 0x12,
	0x06, 0x0a, 0x02, 0x47, 0x4d, 0x10, 0x14, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x10, 0x15, 0x2a, 0x32, 0x0a, 0x09, 0x45, 0x50, 0x6c, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x50, 0x54, 0x5f, 0x41, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x45, 0x50, 0x54, 0x5f, 0x49, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x50, 0x54,
	0x5f, 0x57, 0x65, 0x62, 0x10, 0x02, 0x2a, 0x3c, 0x0a, 0x0a, 0x45, 0x53, 0x64, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x75, 0x65, 0x73, 0x74, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70,
	0x6c, 0x65, 0x10, 0x03, 0x2a, 0x39, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x70,
	0x12, 0x0a, 0x0a, 0x06, 0x54, 0x43, 0x42, 0x61, 0x73, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x54, 0x43, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x54,
	0x43, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x10, 0x02, 0x2a,
	0x36, 0x0a, 0x0a, 0x45, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x47, 0x6f, 0x6f, 0x64, 0x10, 0x03, 0x42, 0x08, 0x48, 0x03, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_common_proto_rawDescOnce sync.Once
	file_msg_common_proto_rawDescData = file_msg_common_proto_rawDesc
)

func file_msg_common_proto_rawDescGZIP() []byte {
	file_msg_common_proto_rawDescOnce.Do(func() {
		file_msg_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_common_proto_rawDescData)
	})
	return file_msg_common_proto_rawDescData
}

var file_msg_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_msg_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msg_common_proto_goTypes = []interface{}{
	(Server)(0),           // 0: pb.Server
	(EPlatType)(0),        // 1: pb.EPlatType
	(ESdkNumber)(0),       // 2: pb.ESdkNumber
	(TypeComp)(0),         // 3: pb.TypeComp
	(EPrizeType)(0),       // 4: pb.EPrizeType
	(*PrizeItem)(nil),     // 5: pb.PrizeItem
	(*PrizeItems)(nil),    // 6: pb.PrizeItems
	(*PrizePoolData)(nil), // 7: pb.PrizePoolData
}
var file_msg_common_proto_depIdxs = []int32{
	4, // 0: pb.PrizeItem.Type:type_name -> pb.EPrizeType
	5, // 1: pb.PrizeItems.Items:type_name -> pb.PrizeItem
	4, // 2: pb.PrizePoolData.Type:type_name -> pb.EPrizeType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_msg_common_proto_init() }
func file_msg_common_proto_init() {
	if File_msg_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrizeItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrizeItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrizePoolData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_common_proto_goTypes,
		DependencyIndexes: file_msg_common_proto_depIdxs,
		EnumInfos:         file_msg_common_proto_enumTypes,
		MessageInfos:      file_msg_common_proto_msgTypes,
	}.Build()
	File_msg_common_proto = out.File
	file_msg_common_proto_rawDesc = nil
	file_msg_common_proto_goTypes = nil
	file_msg_common_proto_depIdxs = nil
}
