// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: msg_base.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginCode int32

const (
	LoginCode_LCSuccess        LoginCode = 0
	LoginCode_LCSdkCheckFaild  LoginCode = 1  //sdk检测登录失败
	LoginCode_LCNoGame         LoginCode = 2  //game未启动
	LoginCode_LCCanNotReConn   LoginCode = 3  //不能重连了
	LoginCode_LCCD             LoginCode = 4  //冷却中
	LoginCode_LCFreeze         LoginCode = 5  //封停
	LoginCode_LCClose          LoginCode = 6  //服务器关闭
	LoginCode_LCSDKCtl         LoginCode = 7  //所属的渠道被限制登录
	LoginCode_LCVersionErr     LoginCode = 8  //版本号错误
	LoginCode_LCServerFull     LoginCode = 9  //服务器人数达到上限
	LoginCode_LCServerBusy     LoginCode = 10 //服务器繁忙
	LoginCode_LCCanNotRegister LoginCode = 11 //不能注册了新玩家不让进
	LoginCode_LCBindDev        LoginCode = 12 //绑定设备的账号，登录使用的设备和绑定设备不一致
	LoginCode_LCServerErr      LoginCode = 13 //服务器异常
	LoginCode_LCOtherDevLogin  LoginCode = 14 //其它设备登录，顶号
)

// Enum value maps for LoginCode.
var (
	LoginCode_name = map[int32]string{
		0:  "LCSuccess",
		1:  "LCSdkCheckFaild",
		2:  "LCNoGame",
		3:  "LCCanNotReConn",
		4:  "LCCD",
		5:  "LCFreeze",
		6:  "LCClose",
		7:  "LCSDKCtl",
		8:  "LCVersionErr",
		9:  "LCServerFull",
		10: "LCServerBusy",
		11: "LCCanNotRegister",
		12: "LCBindDev",
		13: "LCServerErr",
		14: "LCOtherDevLogin",
	}
	LoginCode_value = map[string]int32{
		"LCSuccess":        0,
		"LCSdkCheckFaild":  1,
		"LCNoGame":         2,
		"LCCanNotReConn":   3,
		"LCCD":             4,
		"LCFreeze":         5,
		"LCClose":          6,
		"LCSDKCtl":         7,
		"LCVersionErr":     8,
		"LCServerFull":     9,
		"LCServerBusy":     10,
		"LCCanNotRegister": 11,
		"LCBindDev":        12,
		"LCServerErr":      13,
		"LCOtherDevLogin":  14,
	}
)

func (x LoginCode) Enum() *LoginCode {
	p := new(LoginCode)
	*p = x
	return p
}

func (x LoginCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginCode) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_base_proto_enumTypes[0].Descriptor()
}

func (LoginCode) Type() protoreflect.EnumType {
	return &file_msg_base_proto_enumTypes[0]
}

func (x LoginCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginCode.Descriptor instead.
func (LoginCode) EnumDescriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{0}
}

type S2SGameState_GmState int32

const (
	S2SGameState_GmRunning  S2SGameState_GmState = 0
	S2SGameState_GmSaveData S2SGameState_GmState = 1
	S2SGameState_GmClose    S2SGameState_GmState = 2
	S2SGameState_GmTimeOut  S2SGameState_GmState = 3
)

// Enum value maps for S2SGameState_GmState.
var (
	S2SGameState_GmState_name = map[int32]string{
		0: "GmRunning",
		1: "GmSaveData",
		2: "GmClose",
		3: "GmTimeOut",
	}
	S2SGameState_GmState_value = map[string]int32{
		"GmRunning":  0,
		"GmSaveData": 1,
		"GmClose":    2,
		"GmTimeOut":  3,
	}
)

func (x S2SGameState_GmState) Enum() *S2SGameState_GmState {
	p := new(S2SGameState_GmState)
	*p = x
	return p
}

func (x S2SGameState_GmState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2SGameState_GmState) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_base_proto_enumTypes[1].Descriptor()
}

func (S2SGameState_GmState) Type() protoreflect.EnumType {
	return &file_msg_base_proto_enumTypes[1]
}

func (x S2SGameState_GmState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2SGameState_GmState.Descriptor instead.
func (S2SGameState_GmState) EnumDescriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{14, 0}
}

type C2SBindAcc_BindAccCode int32

const (
	C2SBindAcc_BindSuccess  C2SBindAcc_BindAccCode = 0 //成功
	C2SBindAcc_GuestIsBind  C2SBindAcc_BindAccCode = 1 //游客账号已经被绑定
	C2SBindAcc_AccIsBind    C2SBindAcc_BindAccCode = 2 //账号已经有角色了
	C2SBindAcc_GuestNotFind C2SBindAcc_BindAccCode = 3 //游客数据出错了
)

// Enum value maps for C2SBindAcc_BindAccCode.
var (
	C2SBindAcc_BindAccCode_name = map[int32]string{
		0: "BindSuccess",
		1: "GuestIsBind",
		2: "AccIsBind",
		3: "GuestNotFind",
	}
	C2SBindAcc_BindAccCode_value = map[string]int32{
		"BindSuccess":  0,
		"GuestIsBind":  1,
		"AccIsBind":    2,
		"GuestNotFind": 3,
	}
)

func (x C2SBindAcc_BindAccCode) Enum() *C2SBindAcc_BindAccCode {
	p := new(C2SBindAcc_BindAccCode)
	*p = x
	return p
}

func (x C2SBindAcc_BindAccCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2SBindAcc_BindAccCode) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_base_proto_enumTypes[2].Descriptor()
}

func (C2SBindAcc_BindAccCode) Type() protoreflect.EnumType {
	return &file_msg_base_proto_enumTypes[2]
}

func (x C2SBindAcc_BindAccCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2SBindAcc_BindAccCode.Descriptor instead.
func (C2SBindAcc_BindAccCode) EnumDescriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{16, 0}
}

type C2SGateHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGateHandle) Reset() {
	*x = C2SGateHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGateHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGateHandle) ProtoMessage() {}

func (x *C2SGateHandle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGateHandle.ProtoReflect.Descriptor instead.
func (*C2SGateHandle) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{0}
}

type C2SAccountHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SAccountHandle) Reset() {
	*x = C2SAccountHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SAccountHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAccountHandle) ProtoMessage() {}

func (x *C2SAccountHandle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAccountHandle.ProtoReflect.Descriptor instead.
func (*C2SAccountHandle) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{1}
}

type C2SGameHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGameHandle) Reset() {
	*x = C2SGameHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGameHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGameHandle) ProtoMessage() {}

func (x *C2SGameHandle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGameHandle.ProtoReflect.Descriptor instead.
func (*C2SGameHandle) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{2}
}

type S2CNone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CNone) Reset() {
	*x = S2CNone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CNone) ProtoMessage() {}

func (x *S2CNone) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CNone.ProtoReflect.Descriptor instead.
func (*S2CNone) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{3}
}

type S2SNone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SNone) Reset() {
	*x = S2SNone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SNone) ProtoMessage() {}

func (x *S2SNone) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SNone.ProtoReflect.Descriptor instead.
func (*S2SNone) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{4}
}

type S2CGateHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CGateHandle) Reset() {
	*x = S2CGateHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGateHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGateHandle) ProtoMessage() {}

func (x *S2CGateHandle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGateHandle.ProtoReflect.Descriptor instead.
func (*S2CGateHandle) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{5}
}

type C2SInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S2CPublic string `protobuf:"bytes,1,opt,name=S2CPublic,proto3" json:"S2CPublic,omitempty"`
	C2SPublic string `protobuf:"bytes,2,opt,name=C2SPublic,proto3" json:"C2SPublic,omitempty"`
}

func (x *C2SInit) Reset() {
	*x = C2SInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SInit) ProtoMessage() {}

func (x *C2SInit) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SInit.ProtoReflect.Descriptor instead.
func (*C2SInit) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{6}
}

func (x *C2SInit) GetS2CPublic() string {
	if x != nil {
		return x.S2CPublic
	}
	return ""
}

func (x *C2SInit) GetC2SPublic() string {
	if x != nil {
		return x.C2SPublic
	}
	return ""
}

type S2CInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S2CPublic string `protobuf:"bytes,1,opt,name=S2CPublic,proto3" json:"S2CPublic,omitempty"`
	C2SPublic string `protobuf:"bytes,2,opt,name=C2SPublic,proto3" json:"C2SPublic,omitempty"`
	Crypto    bool   `protobuf:"varint,3,opt,name=Crypto,proto3" json:"Crypto,omitempty"`
}

func (x *S2CInit) Reset() {
	*x = S2CInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CInit) ProtoMessage() {}

func (x *S2CInit) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CInit.ProtoReflect.Descriptor instead.
func (*S2CInit) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{7}
}

func (x *S2CInit) GetS2CPublic() string {
	if x != nil {
		return x.S2CPublic
	}
	return ""
}

func (x *S2CInit) GetC2SPublic() string {
	if x != nil {
		return x.C2SPublic
	}
	return ""
}

func (x *S2CInit) GetCrypto() bool {
	if x != nil {
		return x.Crypto
	}
	return false
}

type C2SHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CliTime    int64  `protobuf:"zigzag64,1,opt,name=CliTime,proto3" json:"CliTime,omitempty"`
	CliVersion string `protobuf:"bytes,3,opt,name=CliVersion,proto3" json:"CliVersion,omitempty"`
}

func (x *C2SHeartBeat) Reset() {
	*x = C2SHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHeartBeat) ProtoMessage() {}

func (x *C2SHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHeartBeat.ProtoReflect.Descriptor instead.
func (*C2SHeartBeat) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{8}
}

func (x *C2SHeartBeat) GetCliTime() int64 {
	if x != nil {
		return x.CliTime
	}
	return 0
}

func (x *C2SHeartBeat) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

type S2CHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CliTime int64 `protobuf:"zigzag64,1,opt,name=CliTime,proto3" json:"CliTime,omitempty"`
	SerTime int64 `protobuf:"zigzag64,2,opt,name=SerTime,proto3" json:"SerTime,omitempty"`
}

func (x *S2CHeartBeat) Reset() {
	*x = S2CHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHeartBeat) ProtoMessage() {}

func (x *S2CHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHeartBeat.ProtoReflect.Descriptor instead.
func (*S2CHeartBeat) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{9}
}

func (x *S2CHeartBeat) GetCliTime() int64 {
	if x != nil {
		return x.CliTime
	}
	return 0
}

func (x *S2CHeartBeat) GetSerTime() int64 {
	if x != nil {
		return x.SerTime
	}
	return 0
}

// 登录请求
type C2SLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sdk登录需要的数据
	SdkNo     ESdkNumber `protobuf:"varint,1,opt,name=SdkNo,proto3,enum=pb.ESdkNumber" json:"SdkNo,omitempty"`
	Account   string     `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	Token     string     `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	Channel   uint32     `protobuf:"varint,4,opt,name=Channel,proto3" json:"Channel,omitempty"`     //子渠道
	Dev       string     `protobuf:"bytes,5,opt,name=Dev,proto3" json:"Dev,omitempty"`              //设备ID
	Area      uint32     `protobuf:"varint,7,opt,name=Area,proto3" json:"Area,omitempty"`           //选服
	Version   string     `protobuf:"bytes,8,opt,name=Version,proto3" json:"Version,omitempty"`      //客户端版本号
	Reconnect bool       `protobuf:"varint,9,opt,name=Reconnect,proto3" json:"Reconnect,omitempty"` //重连
	// 附加的一些日志数据
	CliInfo *ClientInfo `protobuf:"bytes,10,opt,name=CliInfo,proto3" json:"CliInfo,omitempty"` //客户端信息
}

func (x *C2SLogin) Reset() {
	*x = C2SLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLogin) ProtoMessage() {}

func (x *C2SLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLogin.ProtoReflect.Descriptor instead.
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{10}
}

func (x *C2SLogin) GetSdkNo() ESdkNumber {
	if x != nil {
		return x.SdkNo
	}
	return ESdkNumber_Guest
}

func (x *C2SLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *C2SLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2SLogin) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *C2SLogin) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *C2SLogin) GetArea() uint32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *C2SLogin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *C2SLogin) GetReconnect() bool {
	if x != nil {
		return x.Reconnect
	}
	return false
}

func (x *C2SLogin) GetCliInfo() *ClientInfo {
	if x != nil {
		return x.CliInfo
	}
	return nil
}

type S2CLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code            LoginCode `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.LoginCode" json:"Code,omitempty"`
	GameID          uint32    `protobuf:"varint,2,opt,name=GameID,proto3" json:"GameID,omitempty"`
	OpenTime        int64     `protobuf:"zigzag64,3,opt,name=OpenTime,proto3" json:"OpenTime,omitempty"`
	ServerNowTime   int64     `protobuf:"varint,4,opt,name=ServerNowTime,proto3" json:"ServerNowTime,omitempty"` //服务器当前时间
	ServerBeginTime int64     `protobuf:"varint,5,opt,name=ServerBeginTime,proto3" json:"ServerBeginTime,omitempty"`
	Dev             string    `protobuf:"bytes,6,opt,name=Dev,proto3" json:"Dev,omitempty"`
	RetDesc         string    `protobuf:"bytes,7,opt,name=RetDesc,proto3" json:"RetDesc,omitempty"` //当Ret=LCFreeze，LCClose时，返回描述
	Token           uint32    `protobuf:"varint,8,opt,name=Token,proto3" json:"Token,omitempty"`
	CliVersion      string    `protobuf:"bytes,9,opt,name=CliVersion,proto3" json:"CliVersion,omitempty"`
	Data            *C2SLogin `protobuf:"bytes,10,opt,name=Data,proto3" json:"Data,omitempty"`
	Player          *RoleData `protobuf:"bytes,11,opt,name=Player,proto3" json:"Player,omitempty"`
}

func (x *S2CLogin) Reset() {
	*x = S2CLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CLogin) ProtoMessage() {}

func (x *S2CLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CLogin.ProtoReflect.Descriptor instead.
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{11}
}

func (x *S2CLogin) GetCode() LoginCode {
	if x != nil {
		return x.Code
	}
	return LoginCode_LCSuccess
}

func (x *S2CLogin) GetGameID() uint32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *S2CLogin) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *S2CLogin) GetServerNowTime() int64 {
	if x != nil {
		return x.ServerNowTime
	}
	return 0
}

func (x *S2CLogin) GetServerBeginTime() int64 {
	if x != nil {
		return x.ServerBeginTime
	}
	return 0
}

func (x *S2CLogin) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *S2CLogin) GetRetDesc() string {
	if x != nil {
		return x.RetDesc
	}
	return ""
}

func (x *S2CLogin) GetToken() uint32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *S2CLogin) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

func (x *S2CLogin) GetData() *C2SLogin {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *S2CLogin) GetPlayer() *RoleData {
	if x != nil {
		return x.Player
	}
	return nil
}

type S2SReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *C2SLogin `protobuf:"bytes,1,opt,name=Req,proto3" json:"Req,omitempty"`
	// 客户端不用的
	SesID        uint64   `protobuf:"varint,2,opt,name=SesID,proto3" json:"SesID,omitempty"`
	RoleID       uint64   `protobuf:"varint,3,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	ReConnToken  uint64   `protobuf:"varint,4,opt,name=ReConnToken,proto3" json:"ReConnToken,omitempty"`
	Seq          uint32   `protobuf:"varint,5,opt,name=Seq,proto3" json:"Seq,omitempty"`
	ConnectedAcc []string `protobuf:"bytes,7,rep,name=ConnectedAcc,proto3" json:"ConnectedAcc,omitempty"` //已绑定的账号
}

func (x *S2SReqLogin) Reset() {
	*x = S2SReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SReqLogin) ProtoMessage() {}

func (x *S2SReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SReqLogin.ProtoReflect.Descriptor instead.
func (*S2SReqLogin) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{12}
}

func (x *S2SReqLogin) GetReq() *C2SLogin {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *S2SReqLogin) GetSesID() uint64 {
	if x != nil {
		return x.SesID
	}
	return 0
}

func (x *S2SReqLogin) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *S2SReqLogin) GetReConnToken() uint64 {
	if x != nil {
		return x.ReConnToken
	}
	return 0
}

func (x *S2SReqLogin) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *S2SReqLogin) GetConnectedAcc() []string {
	if x != nil {
		return x.ConnectedAcc
	}
	return nil
}

type AccountData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccID   uint64 `protobuf:"varint,1,opt,name=AccID,proto3" json:"AccID,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *AccountData) Reset() {
	*x = AccountData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountData) ProtoMessage() {}

func (x *AccountData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountData.ProtoReflect.Descriptor instead.
func (*AccountData) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{13}
}

func (x *AccountData) GetAccID() uint64 {
	if x != nil {
		return x.AccID
	}
	return 0
}

func (x *AccountData) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type S2SGameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleCnt  int32                `protobuf:"zigzag32,1,opt,name=RoleCnt,proto3" json:"RoleCnt,omitempty"`
	EndPoint string               `protobuf:"bytes,2,opt,name=EndPoint,proto3" json:"EndPoint,omitempty"`
	State    S2SGameState_GmState `protobuf:"varint,3,opt,name=State,proto3,enum=pb.S2SGameState_GmState" json:"State,omitempty"`
	Time     int64                `protobuf:"zigzag64,4,opt,name=Time,proto3" json:"Time,omitempty"`
	GameID   int32                `protobuf:"zigzag32,5,opt,name=GameID,proto3" json:"GameID,omitempty"`
}

func (x *S2SGameState) Reset() {
	*x = S2SGameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SGameState) ProtoMessage() {}

func (x *S2SGameState) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SGameState.ProtoReflect.Descriptor instead.
func (*S2SGameState) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{14}
}

func (x *S2SGameState) GetRoleCnt() int32 {
	if x != nil {
		return x.RoleCnt
	}
	return 0
}

func (x *S2SGameState) GetEndPoint() string {
	if x != nil {
		return x.EndPoint
	}
	return ""
}

func (x *S2SGameState) GetState() S2SGameState_GmState {
	if x != nil {
		return x.State
	}
	return S2SGameState_GmRunning
}

func (x *S2SGameState) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *S2SGameState) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

type S2CKickRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CKickRole) Reset() {
	*x = S2CKickRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CKickRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CKickRole) ProtoMessage() {}

func (x *S2CKickRole) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CKickRole.ProtoReflect.Descriptor instead.
func (*S2CKickRole) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{15}
}

type C2SBindAcc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SdkToBind    ESdkNumber             `protobuf:"varint,1,opt,name=SdkToBind,proto3,enum=pb.ESdkNumber" json:"SdkToBind,omitempty"`
	AccToBind    string                 `protobuf:"bytes,2,opt,name=AccToBind,proto3" json:"AccToBind,omitempty"`                     //要绑定的账号（google等）
	Ret          C2SBindAcc_BindAccCode `protobuf:"varint,3,opt,name=Ret,proto3,enum=pb.C2SBindAcc_BindAccCode" json:"Ret,omitempty"` //返回结果
	ConnectedAcc []string               `protobuf:"bytes,4,rep,name=ConnectedAcc,proto3" json:"ConnectedAcc,omitempty"`               //已绑定的账号
	Name         string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Prize        []*PrizeItem           `protobuf:"bytes,7,rep,name=Prize,proto3" json:"Prize,omitempty"`
	// 服务器使用
	GuestAccID uint64      `protobuf:"varint,8,opt,name=GuestAccID,proto3" json:"GuestAccID,omitempty"`
	RoleGuid   uint64      `protobuf:"varint,10,opt,name=RoleGuid,proto3" json:"RoleGuid,omitempty"`
	CliInfo    *ClientInfo `protobuf:"bytes,11,opt,name=CliInfo,proto3" json:"CliInfo,omitempty"` //日志
}

func (x *C2SBindAcc) Reset() {
	*x = C2SBindAcc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SBindAcc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SBindAcc) ProtoMessage() {}

func (x *C2SBindAcc) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SBindAcc.ProtoReflect.Descriptor instead.
func (*C2SBindAcc) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{16}
}

func (x *C2SBindAcc) GetSdkToBind() ESdkNumber {
	if x != nil {
		return x.SdkToBind
	}
	return ESdkNumber_Guest
}

func (x *C2SBindAcc) GetAccToBind() string {
	if x != nil {
		return x.AccToBind
	}
	return ""
}

func (x *C2SBindAcc) GetRet() C2SBindAcc_BindAccCode {
	if x != nil {
		return x.Ret
	}
	return C2SBindAcc_BindSuccess
}

func (x *C2SBindAcc) GetConnectedAcc() []string {
	if x != nil {
		return x.ConnectedAcc
	}
	return nil
}

func (x *C2SBindAcc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *C2SBindAcc) GetPrize() []*PrizeItem {
	if x != nil {
		return x.Prize
	}
	return nil
}

func (x *C2SBindAcc) GetGuestAccID() uint64 {
	if x != nil {
		return x.GuestAccID
	}
	return 0
}

func (x *C2SBindAcc) GetRoleGuid() uint64 {
	if x != nil {
		return x.RoleGuid
	}
	return 0
}

func (x *C2SBindAcc) GetCliInfo() *ClientInfo {
	if x != nil {
		return x.CliInfo
	}
	return nil
}

type S2SReqRoleOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID uint64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	GameID uint32 `protobuf:"varint,2,opt,name=GameID,proto3" json:"GameID,omitempty"`
}

func (x *S2SReqRoleOnline) Reset() {
	*x = S2SReqRoleOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SReqRoleOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SReqRoleOnline) ProtoMessage() {}

func (x *S2SReqRoleOnline) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SReqRoleOnline.ProtoReflect.Descriptor instead.
func (*S2SReqRoleOnline) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{17}
}

func (x *S2SReqRoleOnline) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *S2SReqRoleOnline) GetGameID() uint32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

type S2SResRoleOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID uint64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *S2SResRoleOnline) Reset() {
	*x = S2SResRoleOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SResRoleOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SResRoleOnline) ProtoMessage() {}

func (x *S2SResRoleOnline) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SResRoleOnline.ProtoReflect.Descriptor instead.
func (*S2SResRoleOnline) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{18}
}

func (x *S2SResRoleOnline) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type S2SReqConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SReqConfig) Reset() {
	*x = S2SReqConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SReqConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SReqConfig) ProtoMessage() {}

func (x *S2SReqConfig) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SReqConfig.ProtoReflect.Descriptor instead.
func (*S2SReqConfig) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{19}
}

type S2SResConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *S2SResConfig) Reset() {
	*x = S2SResConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SResConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SResConfig) ProtoMessage() {}

func (x *S2SResConfig) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SResConfig.ProtoReflect.Descriptor instead.
func (*S2SResConfig) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{20}
}

func (x *S2SResConfig) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type S2SKickAcc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc uint64 `protobuf:"varint,1,opt,name=Acc,proto3" json:"Acc,omitempty"`
}

func (x *S2SKickAcc) Reset() {
	*x = S2SKickAcc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SKickAcc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SKickAcc) ProtoMessage() {}

func (x *S2SKickAcc) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SKickAcc.ProtoReflect.Descriptor instead.
func (*S2SKickAcc) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{21}
}

func (x *S2SKickAcc) GetAcc() uint64 {
	if x != nil {
		return x.Acc
	}
	return 0
}

type S2SKickRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SKickRole) Reset() {
	*x = S2SKickRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SKickRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SKickRole) ProtoMessage() {}

func (x *S2SKickRole) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SKickRole.ProtoReflect.Descriptor instead.
func (*S2SKickRole) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{22}
}

type C2SClientReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SClientReady) Reset() {
	*x = C2SClientReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SClientReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SClientReady) ProtoMessage() {}

func (x *C2SClientReady) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SClientReady.ProtoReflect.Descriptor instead.
func (*C2SClientReady) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{23}
}

type S2CDayChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CDayChange) Reset() {
	*x = S2CDayChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CDayChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDayChange) ProtoMessage() {}

func (x *S2CDayChange) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDayChange.ProtoReflect.Descriptor instead.
func (*S2CDayChange) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{24}
}

type S2CDataReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CDataReset) Reset() {
	*x = S2CDataReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CDataReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDataReset) ProtoMessage() {}

func (x *S2CDataReset) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDataReset.ProtoReflect.Descriptor instead.
func (*S2CDataReset) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{25}
}

type S2SRelayToRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID uint32 `protobuf:"varint,1,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *S2SRelayToRole) Reset() {
	*x = S2SRelayToRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SRelayToRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SRelayToRole) ProtoMessage() {}

func (x *S2SRelayToRole) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SRelayToRole.ProtoReflect.Descriptor instead.
func (*S2SRelayToRole) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{26}
}

func (x *S2SRelayToRole) GetMsgID() uint32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *S2SRelayToRole) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// -----------------离线事件---------------------------//
type S2SOfflineEvt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role      uint64 `protobuf:"varint,1,opt,name=Role,proto3" json:"Role,omitempty"`
	Type      uint32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	ProtoName string `protobuf:"bytes,4,opt,name=ProtoName,proto3" json:"ProtoName,omitempty"`
}

func (x *S2SOfflineEvt) Reset() {
	*x = S2SOfflineEvt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SOfflineEvt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SOfflineEvt) ProtoMessage() {}

func (x *S2SOfflineEvt) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SOfflineEvt.ProtoReflect.Descriptor instead.
func (*S2SOfflineEvt) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{27}
}

func (x *S2SOfflineEvt) GetRole() uint64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *S2SOfflineEvt) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *S2SOfflineEvt) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *S2SOfflineEvt) GetProtoName() string {
	if x != nil {
		return x.ProtoName
	}
	return ""
}

type C2SWithoutRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SWithoutRole) Reset() {
	*x = C2SWithoutRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SWithoutRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SWithoutRole) ProtoMessage() {}

func (x *C2SWithoutRole) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SWithoutRole.ProtoReflect.Descriptor instead.
func (*C2SWithoutRole) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{28}
}

// ---------------------------
type MsgForwardToRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID    uint32 `protobuf:"varint,1,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	RoleGuid uint64 `protobuf:"varint,2,opt,name=RoleGuid,proto3" json:"RoleGuid,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *MsgForwardToRole) Reset() {
	*x = MsgForwardToRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgForwardToRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgForwardToRole) ProtoMessage() {}

func (x *MsgForwardToRole) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgForwardToRole.ProtoReflect.Descriptor instead.
func (*MsgForwardToRole) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{29}
}

func (x *MsgForwardToRole) GetMsgID() uint32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *MsgForwardToRole) GetRoleGuid() uint64 {
	if x != nil {
		return x.RoleGuid
	}
	return 0
}

func (x *MsgForwardToRole) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type S2SRoleOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc    string `protobuf:"bytes,1,opt,name=Acc,proto3" json:"Acc,omitempty"`
	RoleID uint64 `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Seq    int32  `protobuf:"varint,3,opt,name=Seq,proto3" json:"Seq,omitempty"`
}

func (x *S2SRoleOffline) Reset() {
	*x = S2SRoleOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SRoleOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SRoleOffline) ProtoMessage() {}

func (x *S2SRoleOffline) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SRoleOffline.ProtoReflect.Descriptor instead.
func (*S2SRoleOffline) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{30}
}

func (x *S2SRoleOffline) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

func (x *S2SRoleOffline) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *S2SRoleOffline) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MsgServerCloseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Close    bool              `protobuf:"varint,1,opt,name=Close,proto3" json:"Close,omitempty"`
	Tips     map[uint32]string `protobuf:"bytes,2,rep,name=Tips,proto3" json:"Tips,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OpenTime int64             `protobuf:"varint,3,opt,name=OpenTime,proto3" json:"OpenTime,omitempty"`
}

func (x *MsgServerCloseInfo) Reset() {
	*x = MsgServerCloseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgServerCloseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgServerCloseInfo) ProtoMessage() {}

func (x *MsgServerCloseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgServerCloseInfo.ProtoReflect.Descriptor instead.
func (*MsgServerCloseInfo) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{31}
}

func (x *MsgServerCloseInfo) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *MsgServerCloseInfo) GetTips() map[uint32]string {
	if x != nil {
		return x.Tips
	}
	return nil
}

func (x *MsgServerCloseInfo) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

type MsgServerClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn   uint32                         `protobuf:"varint,1,opt,name=Sn,proto3" json:"Sn,omitempty"`
	Data map[uint32]*MsgServerCloseInfo `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //维护提示
}

func (x *MsgServerClose) Reset() {
	*x = MsgServerClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgServerClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgServerClose) ProtoMessage() {}

func (x *MsgServerClose) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgServerClose.ProtoReflect.Descriptor instead.
func (*MsgServerClose) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{32}
}

func (x *MsgServerClose) GetSn() uint32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MsgServerClose) GetData() map[uint32]*MsgServerCloseInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 日志需求(客户端在相关协议中携带，比如登陆、充值订单、)
type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DevID      string `protobuf:"bytes,1,opt,name=DevID,proto3" json:"DevID,omitempty"`           //设备ID
	AdvType    string `protobuf:"bytes,2,opt,name=AdvType,proto3" json:"AdvType,omitempty"`       //广告类型
	PhoneModel string `protobuf:"bytes,3,opt,name=PhoneModel,proto3" json:"PhoneModel,omitempty"` //客户端机型
	SysVersion string `protobuf:"bytes,4,opt,name=SysVersion,proto3" json:"SysVersion,omitempty"` //客户端机型版本号
	Machine    string `protobuf:"bytes,5,opt,name=Machine,proto3" json:"Machine,omitempty"`       //客户端系统完整信息json串
	Ip         string `protobuf:"bytes,6,opt,name=Ip,proto3" json:"Ip,omitempty"`                 //客户端Ip
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{33}
}

func (x *ClientInfo) GetDevID() string {
	if x != nil {
		return x.DevID
	}
	return ""
}

func (x *ClientInfo) GetAdvType() string {
	if x != nil {
		return x.AdvType
	}
	return ""
}

func (x *ClientInfo) GetPhoneModel() string {
	if x != nil {
		return x.PhoneModel
	}
	return ""
}

func (x *ClientInfo) GetSysVersion() string {
	if x != nil {
		return x.SysVersion
	}
	return ""
}

func (x *ClientInfo) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *ClientInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RoleInDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RoleInDb) Reset() {
	*x = RoleInDb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_base_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInDb) ProtoMessage() {}

func (x *RoleInDb) ProtoReflect() protoreflect.Message {
	mi := &file_msg_base_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInDb.ProtoReflect.Descriptor instead.
func (*RoleInDb) Descriptor() ([]byte, []int) {
	return file_msg_base_proto_rawDescGZIP(), []int{34}
}

func (x *RoleInDb) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RoleInDb) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_msg_base_proto protoreflect.FileDescriptor

var file_msg_base_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x47,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x32, 0x53,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x0f, 0x0a,
	0x0d, 0x43, 0x32, 0x53, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x09,
	0x0a, 0x07, 0x53, 0x32, 0x43, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x32, 0x53,
	0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x47, 0x61, 0x74, 0x65, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x07, 0x43, 0x32, 0x53, 0x49, 0x6e, 0x69, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x32, 0x43, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x32, 0x53, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x43, 0x32, 0x53, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22, 0x5d, 0x0a, 0x07,
	0x53, 0x32, 0x43, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x32, 0x43, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x32, 0x53, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0c, 0x43,
	0x32, 0x53, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6c, 0x69, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x43, 0x6c,
	0x69, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6c, 0x69, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x43, 0x6c, 0x69, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x12,
	0x52, 0x07, 0x53, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x82, 0x02, 0x0a, 0x08, 0x43, 0x32,
	0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x05, 0x53, 0x64, 0x6b, 0x4e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x53, 0x64, 0x6b, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x05, 0x53, 0x64, 0x6b, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x76, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x65, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x43, 0x6c, 0x69, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x43, 0x6c, 0x69, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xdb,
	0x02, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x77, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x44, 0x65, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x32, 0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0xb3, 0x01, 0x0a,
	0x0b, 0x53, 0x32, 0x53, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x32, 0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x65, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x65, 0x73,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x52, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x53, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x22,
	0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x63, 0x63, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41,
	0x63, 0x63, 0x22, 0x3d, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x63, 0x63, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x41, 0x63, 0x63, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0xe6, 0x01, 0x0a, 0x0c, 0x53, 0x32, 0x53, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x11, 0x52, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x32, 0x53,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x11, 0x52, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x22, 0x44, 0x0a, 0x07, 0x47, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x47, 0x6d, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x47, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x47, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x47,
	0x6d, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x10, 0x03, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x32,
	0x43, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x9b, 0x03, 0x0a, 0x0a, 0x43, 0x32,
	0x53, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x12, 0x2c, 0x0a, 0x09, 0x53, 0x64, 0x6b, 0x54,
	0x6f, 0x42, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x53, 0x64, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x09, 0x53, 0x64, 0x6b,
	0x54, 0x6f, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x54, 0x6f, 0x42,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x63, 0x63, 0x54, 0x6f,
	0x42, 0x69, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x32, 0x53, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63,
	0x63, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52,
	0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41,
	0x63, 0x63, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x41, 0x63, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x50, 0x72,
	0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x72, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x47, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x63, 0x49, 0x44, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x47, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x63, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x75, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x43,
	0x6c, 0x69, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x43, 0x6c,
	0x69, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x50, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x73,
	0x42, 0x69, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x49, 0x73, 0x42,
	0x69, 0x6e, 0x64, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f,
	0x74, 0x46, 0x69, 0x6e, 0x64, 0x10, 0x03, 0x22, 0x42, 0x0a, 0x10, 0x53, 0x32, 0x53, 0x52, 0x65,
	0x71, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x10, 0x53,
	0x32, 0x53, 0x52, 0x65, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x32, 0x53, 0x52, 0x65,
	0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x32, 0x53, 0x52, 0x65,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0a, 0x53,
	0x32, 0x53, 0x4b, 0x69, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x41, 0x63, 0x63, 0x22, 0x0d, 0x0a, 0x0b, 0x53,
	0x32, 0x53, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x32,
	0x53, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x0e, 0x0a, 0x0c,
	0x53, 0x32, 0x43, 0x44, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x0e, 0x0a, 0x0c,
	0x53, 0x32, 0x43, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x65, 0x74, 0x22, 0x3a, 0x0a, 0x0e,
	0x53, 0x32, 0x53, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4d,
	0x73, 0x67, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x69, 0x0a, 0x0d, 0x53, 0x32, 0x53, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x76, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x58, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x54, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x47, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x4c, 0x0a, 0x0e, 0x53, 0x32, 0x53, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x41, 0x63, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x53,
	0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x71, 0x22, 0xb5, 0x01,
	0x0a, 0x12, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x54, 0x69,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x54, 0x69, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x54, 0x69, 0x70, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x37, 0x0a, 0x09,
	0x54, 0x69, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa3, 0x01, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x53, 0x6e, 0x12, 0x30, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x4f, 0x0a, 0x09, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa6, 0x01, 0x0a, 0x0a,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65,
	0x76, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x44, 0x65, 0x76, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x76, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x64, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x79,
	0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x53, 0x79, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x70, 0x22, 0x2e, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x44, 0x62,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x2a, 0x85, 0x02, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x43, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x43, 0x53, 0x64, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46,
	0x61, 0x69, 0x6c, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x43, 0x4e, 0x6f, 0x47, 0x61,
	0x6d, 0x65, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x43, 0x43, 0x61, 0x6e, 0x4e, 0x6f, 0x74,
	0x52, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x43, 0x43, 0x44,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x43, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x10, 0x05,
	0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x43, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x06, 0x12, 0x0c, 0x0a,
	0x08, 0x4c, 0x43, 0x53, 0x44, 0x4b, 0x43, 0x74, 0x6c, 0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x4c,
	0x43, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x10, 0x08, 0x12, 0x10, 0x0a,
	0x0c, 0x4c, 0x43, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x09, 0x12,
	0x10, 0x0a, 0x0c, 0x4c, 0x43, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x75, 0x73, 0x79, 0x10,
	0x0a, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x43, 0x43, 0x61, 0x6e, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x43, 0x42, 0x69, 0x6e,
	0x64, 0x44, 0x65, 0x76, 0x10, 0x0c, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x43, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x45, 0x72, 0x72, 0x10, 0x0d, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x43, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x44, 0x65, 0x76, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x0e, 0x42, 0x08, 0x48, 0x03,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_base_proto_rawDescOnce sync.Once
	file_msg_base_proto_rawDescData = file_msg_base_proto_rawDesc
)

func file_msg_base_proto_rawDescGZIP() []byte {
	file_msg_base_proto_rawDescOnce.Do(func() {
		file_msg_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_base_proto_rawDescData)
	})
	return file_msg_base_proto_rawDescData
}

var file_msg_base_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_msg_base_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_msg_base_proto_goTypes = []interface{}{
	(LoginCode)(0),              // 0: pb.LoginCode
	(S2SGameState_GmState)(0),   // 1: pb.S2SGameState.GmState
	(C2SBindAcc_BindAccCode)(0), // 2: pb.C2SBindAcc.BindAccCode
	(*C2SGateHandle)(nil),       // 3: pb.C2SGateHandle
	(*C2SAccountHandle)(nil),    // 4: pb.C2SAccountHandle
	(*C2SGameHandle)(nil),       // 5: pb.C2SGameHandle
	(*S2CNone)(nil),             // 6: pb.S2CNone
	(*S2SNone)(nil),             // 7: pb.S2SNone
	(*S2CGateHandle)(nil),       // 8: pb.S2CGateHandle
	(*C2SInit)(nil),             // 9: pb.C2SInit
	(*S2CInit)(nil),             // 10: pb.S2CInit
	(*C2SHeartBeat)(nil),        // 11: pb.C2SHeartBeat
	(*S2CHeartBeat)(nil),        // 12: pb.S2CHeartBeat
	(*C2SLogin)(nil),            // 13: pb.C2SLogin
	(*S2CLogin)(nil),            // 14: pb.S2CLogin
	(*S2SReqLogin)(nil),         // 15: pb.S2SReqLogin
	(*AccountData)(nil),         // 16: pb.AccountData
	(*S2SGameState)(nil),        // 17: pb.S2SGameState
	(*S2CKickRole)(nil),         // 18: pb.S2CKickRole
	(*C2SBindAcc)(nil),          // 19: pb.C2SBindAcc
	(*S2SReqRoleOnline)(nil),    // 20: pb.S2SReqRoleOnline
	(*S2SResRoleOnline)(nil),    // 21: pb.S2SResRoleOnline
	(*S2SReqConfig)(nil),        // 22: pb.S2SReqConfig
	(*S2SResConfig)(nil),        // 23: pb.S2SResConfig
	(*S2SKickAcc)(nil),          // 24: pb.S2SKickAcc
	(*S2SKickRole)(nil),         // 25: pb.S2SKickRole
	(*C2SClientReady)(nil),      // 26: pb.C2SClientReady
	(*S2CDayChange)(nil),        // 27: pb.S2CDayChange
	(*S2CDataReset)(nil),        // 28: pb.S2CDataReset
	(*S2SRelayToRole)(nil),      // 29: pb.S2SRelayToRole
	(*S2SOfflineEvt)(nil),       // 30: pb.S2SOfflineEvt
	(*C2SWithoutRole)(nil),      // 31: pb.C2SWithoutRole
	(*MsgForwardToRole)(nil),    // 32: pb.MsgForwardToRole
	(*S2SRoleOffline)(nil),      // 33: pb.S2SRoleOffline
	(*MsgServerCloseInfo)(nil),  // 34: pb.MsgServerCloseInfo
	(*MsgServerClose)(nil),      // 35: pb.MsgServerClose
	(*ClientInfo)(nil),          // 36: pb.ClientInfo
	(*RoleInDb)(nil),            // 37: pb.RoleInDb
	nil,                         // 38: pb.MsgServerCloseInfo.TipsEntry
	nil,                         // 39: pb.MsgServerClose.DataEntry
	(ESdkNumber)(0),             // 40: pb.ESdkNumber
	(*RoleData)(nil),            // 41: pb.RoleData
	(*PrizeItem)(nil),           // 42: pb.PrizeItem
}
var file_msg_base_proto_depIdxs = []int32{
	40, // 0: pb.C2SLogin.SdkNo:type_name -> pb.ESdkNumber
	36, // 1: pb.C2SLogin.CliInfo:type_name -> pb.ClientInfo
	0,  // 2: pb.S2CLogin.Code:type_name -> pb.LoginCode
	13, // 3: pb.S2CLogin.Data:type_name -> pb.C2SLogin
	41, // 4: pb.S2CLogin.Player:type_name -> pb.RoleData
	13, // 5: pb.S2SReqLogin.Req:type_name -> pb.C2SLogin
	1,  // 6: pb.S2SGameState.State:type_name -> pb.S2SGameState.GmState
	40, // 7: pb.C2SBindAcc.SdkToBind:type_name -> pb.ESdkNumber
	2,  // 8: pb.C2SBindAcc.Ret:type_name -> pb.C2SBindAcc.BindAccCode
	42, // 9: pb.C2SBindAcc.Prize:type_name -> pb.PrizeItem
	36, // 10: pb.C2SBindAcc.CliInfo:type_name -> pb.ClientInfo
	38, // 11: pb.MsgServerCloseInfo.Tips:type_name -> pb.MsgServerCloseInfo.TipsEntry
	39, // 12: pb.MsgServerClose.Data:type_name -> pb.MsgServerClose.DataEntry
	34, // 13: pb.MsgServerClose.DataEntry.value:type_name -> pb.MsgServerCloseInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_msg_base_proto_init() }
func file_msg_base_proto_init() {
	if File_msg_base_proto != nil {
		return
	}
	file_msg_common_proto_init()
	file_msg_player_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGateHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SAccountHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGameHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CNone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SNone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGateHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SGameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CKickRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SBindAcc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SReqRoleOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SResRoleOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SReqConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SResConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SKickAcc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SKickRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SClientReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CDayChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CDataReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SRelayToRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SOfflineEvt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SWithoutRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgForwardToRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SRoleOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgServerCloseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgServerClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_base_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleInDb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_base_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_base_proto_goTypes,
		DependencyIndexes: file_msg_base_proto_depIdxs,
		EnumInfos:         file_msg_base_proto_enumTypes,
		MessageInfos:      file_msg_base_proto_msgTypes,
	}.Build()
	File_msg_base_proto = out.File
	file_msg_base_proto_rawDesc = nil
	file_msg_base_proto_goTypes = nil
	file_msg_base_proto_depIdxs = nil
}
