// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NatsMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID   uint32 `protobuf:"varint,1,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	SerID   int32  `protobuf:"zigzag32,3,opt,name=SerID,proto3" json:"SerID,omitempty"`
	SerType Server `protobuf:"varint,4,opt,name=SerType,proto3,enum=pb.Server" json:"SerType,omitempty"`
	RoleID  uint64 `protobuf:"varint,5,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	SesID   uint64 `protobuf:"varint,6,opt,name=SesID,proto3" json:"SesID,omitempty"`
	Forward bool   `protobuf:"varint,7,opt,name=Forward,proto3" json:"Forward,omitempty"`
}

func (x *NatsMsg) Reset() {
	*x = NatsMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NatsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsMsg) ProtoMessage() {}

func (x *NatsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsMsg.ProtoReflect.Descriptor instead.
func (*NatsMsg) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *NatsMsg) GetMsgID() uint32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *NatsMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NatsMsg) GetSerID() int32 {
	if x != nil {
		return x.SerID
	}
	return 0
}

func (x *NatsMsg) GetSerType() Server {
	if x != nil {
		return x.SerType
	}
	return Server_Gateway
}

func (x *NatsMsg) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *NatsMsg) GetSesID() uint64 {
	if x != nil {
		return x.SesID
	}
	return 0
}

func (x *NatsMsg) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

type SrvMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     uint32 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Msg    []byte `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RoleID uint64 `protobuf:"varint,4,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *SrvMsg) Reset() {
	*x = SrvMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrvMsg) ProtoMessage() {}

func (x *SrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrvMsg.ProtoReflect.Descriptor instead.
func (*SrvMsg) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *SrvMsg) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SrvMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SrvMsg) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type SrvMsgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*SrvMsg `protobuf:"bytes,1,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
}

func (x *SrvMsgs) Reset() {
	*x = SrvMsgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrvMsgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrvMsgs) ProtoMessage() {}

func (x *SrvMsgs) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrvMsgs.ProtoReflect.Descriptor instead.
func (*SrvMsgs) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *SrvMsgs) GetMsgs() []*SrvMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x07, 0x4e, 0x61, 0x74, 0x73, 0x4d, 0x73,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x53, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x24, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x07,
	0x53, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x65, 0x73, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x53, 0x65, 0x73, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x22,
	0x42, 0x0a, 0x06, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x07, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x73, 0x12, 0x1e,
	0x0a, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x32, 0x34,
	0x0a, 0x0a, 0x53, 0x72, 0x76, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x06,
	0x53, 0x72, 0x76, 0x53, 0x72, 0x76, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x72, 0x76, 0x4d,
	0x73, 0x67, 0x73, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x72, 0x76, 0x4d, 0x73, 0x67, 0x73,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x08, 0x48, 0x03, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []interface{}{
	(*NatsMsg)(nil), // 0: pb.NatsMsg
	(*SrvMsg)(nil),  // 1: pb.SrvMsg
	(*SrvMsgs)(nil), // 2: pb.SrvMsgs
	(Server)(0),     // 3: pb.Server
}
var file_service_proto_depIdxs = []int32{
	3, // 0: pb.NatsMsg.SerType:type_name -> pb.Server
	1, // 1: pb.SrvMsgs.Msgs:type_name -> pb.SrvMsg
	2, // 2: pb.SrvService.SrvSrv:input_type -> pb.SrvMsgs
	2, // 3: pb.SrvService.SrvSrv:output_type -> pb.SrvMsgs
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_msg_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NatsMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrvMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrvMsgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
