syntax = "proto3";

option optimize_for = LITE_RUNTIME;
option go_package = "./pb";

//---------------说明---------------------------
//公用结构,
//----------------------------------------------

package pb;

enum Server{
	Gateway = 0;
	Account = 1;
	Game = 2;
	Center = 3;
	Log = 4;
	GM = 20;
	Robot = 21;
	Max = 22;
}

enum EPlatType {
	EPT_And = 0;	//安卓
	EPT_IOS = 1;	//苹果
	EPT_Web = 2;	//网页
}

//sdk
enum SdkType{
	Guest = 0;					//游客
	Facebook = 1;				//facebook
	Google = 2;					//原生google
	Apple = 3;					//原生苹果
}

enum TypeComp{
	TCBase = 0;
	TCExample = 1;
	TCEmptyExample = 2;
	TCDebug = 3;

	TCMax = 5; //保持最大
}
